// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.19.1
// source: opentelemetry/proto/collector/logs/v1/logs_service.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ResourceLogs } from "../../../logs/v1/logs.js";
function createBaseExportLogsServiceRequest() {
    return { resourceLogs: [] };
}
export const ExportLogsServiceRequest = {
    encode(message, writer = new BinaryWriter()) {
        for (const v of message.resourceLogs) {
            ResourceLogs.encode(v, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseExportLogsServiceRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.resourceLogs.push(ResourceLogs.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            resourceLogs: globalThis.Array.isArray(object?.resourceLogs)
                ? object.resourceLogs.map((e) => ResourceLogs.fromJSON(e))
                : globalThis.Array.isArray(object?.resource_logs)
                    ? object.resource_logs.map((e) => ResourceLogs.fromJSON(e))
                    : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.resourceLogs?.length) {
            obj.resourceLogs = message.resourceLogs.map((e) => ResourceLogs.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return ExportLogsServiceRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseExportLogsServiceRequest();
        message.resourceLogs = object.resourceLogs?.map((e) => ResourceLogs.fromPartial(e)) || [];
        return message;
    },
};
function createBaseExportLogsServiceResponse() {
    return { partialSuccess: undefined };
}
export const ExportLogsServiceResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.partialSuccess !== undefined) {
            ExportLogsPartialSuccess.encode(message.partialSuccess, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseExportLogsServiceResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.partialSuccess = ExportLogsPartialSuccess.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            partialSuccess: isSet(object.partialSuccess)
                ? ExportLogsPartialSuccess.fromJSON(object.partialSuccess)
                : isSet(object.partial_success)
                    ? ExportLogsPartialSuccess.fromJSON(object.partial_success)
                    : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.partialSuccess !== undefined) {
            obj.partialSuccess = ExportLogsPartialSuccess.toJSON(message.partialSuccess);
        }
        return obj;
    },
    create(base) {
        return ExportLogsServiceResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseExportLogsServiceResponse();
        message.partialSuccess = (object.partialSuccess !== undefined && object.partialSuccess !== null)
            ? ExportLogsPartialSuccess.fromPartial(object.partialSuccess)
            : undefined;
        return message;
    },
};
function createBaseExportLogsPartialSuccess() {
    return { rejectedLogRecords: "0", errorMessage: "" };
}
export const ExportLogsPartialSuccess = {
    encode(message, writer = new BinaryWriter()) {
        if (message.rejectedLogRecords !== "0") {
            writer.uint32(8).int64(message.rejectedLogRecords);
        }
        if (message.errorMessage !== "") {
            writer.uint32(18).string(message.errorMessage);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseExportLogsPartialSuccess();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.rejectedLogRecords = reader.int64().toString();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.errorMessage = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            rejectedLogRecords: isSet(object.rejectedLogRecords)
                ? globalThis.String(object.rejectedLogRecords)
                : isSet(object.rejected_log_records)
                    ? globalThis.String(object.rejected_log_records)
                    : "0",
            errorMessage: isSet(object.errorMessage)
                ? globalThis.String(object.errorMessage)
                : isSet(object.error_message)
                    ? globalThis.String(object.error_message)
                    : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.rejectedLogRecords !== "0") {
            obj.rejectedLogRecords = message.rejectedLogRecords;
        }
        if (message.errorMessage !== "") {
            obj.errorMessage = message.errorMessage;
        }
        return obj;
    },
    create(base) {
        return ExportLogsPartialSuccess.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseExportLogsPartialSuccess();
        message.rejectedLogRecords = object.rejectedLogRecords ?? "0";
        message.errorMessage = object.errorMessage ?? "";
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
