#!/usr/bin/env python3
"""Generate a non-secret OTel connection contract and Kubernetes overlay."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any


GENERATOR_NAME = "otel-generate-app-collector-config"
LEGACY_GENERATOR_NAME = "otel-generate-config"
GENERATOR_VERSION = "1.0.0"
OWNER_MARKER = f"# Generated by {GENERATOR_NAME}. Do not edit."
HASH_PREFIX = f"# {GENERATOR_NAME}-input-sha256: "
LEGACY_OWNER_MARKER = f"# Generated by {LEGACY_GENERATOR_NAME}. Do not edit."
LEGACY_HASH_PREFIX = f"# {LEGACY_GENERATOR_NAME}-input-sha256: "
MANAGED_PREFIXES = (
    f"{OWNER_MARKER}\n{HASH_PREFIX}",
    f"{LEGACY_OWNER_MARKER}\n{LEGACY_HASH_PREFIX}",
)
DNS_LABEL = re.compile(r"^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")
REALM = re.compile(r"^[a-z][a-z0-9-]{0,30}[a-z0-9]$")
DOMAIN = re.compile(
    r"^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)*"
    r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$"
)
YAML_KEY = re.compile(r"^[A-Za-z_][A-Za-z0-9_.-]*$")
MANAGED_FILES = (
    Path("otel-connection.yaml"),
    Path("kubernetes/kustomization.yaml"),
    Path("kubernetes/otel-env-patch.yaml"),
)
SCAFFOLD_WORKLOAD_FILE = Path("kubernetes/workload.yaml")
YAML_DOCUMENT_BOUNDARY = re.compile(
    r"^---(?:\s+#.*)?\s*$", re.MULTILINE
)
COLLECTOR_RELEASE_NAME_MAX_LENGTH = 47
KUSTOMIZE_TIMEOUT_SECONDS = 60
SECRET_NAME_ERROR = "invalid Kubernetes Secret name"
OTEL_ENV_CONFLICT_ERROR = (
    "selected container has conflicting OpenTelemetry environment configuration"
)
KUSTOMIZATION_NAMES = (
    "kustomization.yaml",
    "kustomization.yml",
    "Kustomization",
)
REMOTE_KUSTOMIZE_REFERENCE = re.compile(
    r"(?:[A-Za-z][A-Za-z0-9+.-]*://|git@|"
    r"(?:^|[\s\"'])github\.com/|\?ref=)",
    re.MULTILINE,
)


def reject_token_argument(argv: list[str] | None) -> list[str]:
    arguments = list(sys.argv[1:] if argv is None else argv)
    if any(
        argument == "--token" or argument.startswith("--token=")
        for argument in arguments
    ):
        raise ValueError(
            "--token is forbidden; pass only a Kubernetes Secret name"
        )
    for index, argument in enumerate(arguments):
        if argument in {"--secret-name", "--existing-secret"}:
            if (
                index + 1 >= len(arguments)
                or arguments[index + 1].startswith("--")
                or not DNS_LABEL.fullmatch(arguments[index + 1])
            ):
                raise ValueError(SECRET_NAME_ERROR)
        elif (
            argument.startswith("--secret-name=")
            or argument.startswith("--existing-secret=")
        ):
            if not DNS_LABEL.fullmatch(argument.partition("=")[2]):
                raise ValueError(SECRET_NAME_ERROR)
    return arguments


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    arguments = reject_token_argument(argv)
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--app", type=Path, default=Path("."))
    parser.add_argument("--output", type=Path)
    parser.add_argument("--workspace-root", type=Path)
    parser.add_argument("--platform", choices=("kubernetes",), default="kubernetes")
    parser.add_argument("--realm", required=True)
    parser.add_argument("--collector-namespace", default="observability")
    parser.add_argument("--collector-release", default="splunk-otel")
    parser.add_argument(
        "--topology", choices=("gateway", "agent-service"), default="gateway"
    )
    parser.add_argument(
        "--secret-name",
        "--existing-secret",
        dest="secret_name",
        required=True,
        help="Name of the Collector-only token Secret; no token is read.",
    )
    parser.add_argument("--collector-service")
    parser.add_argument("--collector-evidence", type=Path)
    parser.add_argument("--cluster-domain", default="cluster.local")
    parser.add_argument(
        "--protocol", choices=("http/protobuf", "grpc"), default="http/protobuf"
    )
    parser.add_argument("--base", type=Path)
    parser.add_argument(
        "--scaffold-workload",
        action="store_true",
        help=(
            "Generate a reviewable Kubernetes workload scaffold when the "
            "application repo has no existing workload base."
        ),
    )
    parser.add_argument("--application-namespace")
    parser.add_argument(
        "--workload-kind",
        choices=("Deployment", "StatefulSet", "DaemonSet"),
        default="Deployment",
    )
    parser.add_argument("--workload-name")
    parser.add_argument("--container")
    parser.add_argument("--image")
    parser.add_argument("--container-port", type=int)
    parser.add_argument("--service-name")
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args(arguments)


def validate_dns_label(label: str, value: str) -> None:
    if not DNS_LABEL.fullmatch(value):
        raise ValueError(f"invalid {label}: {value!r}")


def validate_secret_name(value: str) -> None:
    if not DNS_LABEL.fullmatch(value):
        raise ValueError(SECRET_NAME_ERROR)


def dns_label_from_text(value: str, *, fallback: str) -> str:
    label = re.sub(r"[^a-z0-9-]+", "-", value.lower()).strip("-")
    label = re.sub(r"-+", "-", label)
    if len(label) > 63:
        label = label[:63].rstrip("-")
    if not label or not DNS_LABEL.fullmatch(label):
        return fallback
    return label


def is_within(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
    except ValueError:
        return False
    return True


def find_workspace_root(start: Path) -> Path:
    for candidate in (start, *start.parents):
        if (candidate / ".git").exists():
            return candidate.resolve()
    return start.resolve()


def resolve_from(path: Path, base: Path, *, strict: bool) -> Path:
    candidate = path if path.is_absolute() else base / path
    return candidate.resolve(strict=strict)


def reject_symlink_components(path: Path, stop: Path) -> None:
    absolute = Path(os.path.abspath(path))
    cursor = absolute
    while True:
        if cursor.is_symlink():
            raise ValueError(f"path contains a symlink component: {cursor}")
        if cursor.resolve(strict=False) == stop or cursor.parent == cursor:
            break
        cursor = cursor.parent


def yaml_input_scalar(
    text: str, key: str, *, indent: int | None = None
) -> str | None:
    indentation = rf" {{{indent}}}" if indent is not None else r"\s*"
    match = re.search(
        rf"^{indentation}{re.escape(key)}:\s*(?P<value>[^#\r\n]*?)\s*(?:#.*)?$",
        text,
        re.MULTILINE,
    )
    if not match:
        return None
    value = match.group("value").strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        value = value[1:-1]
    return value


def yaml_section(text: str, key: str) -> tuple[str, int] | None:
    lines = text.splitlines()
    for index, line in enumerate(lines):
        match = re.fullmatch(rf"(?P<indent> *){re.escape(key)}:\s*(?:#.*)?", line)
        if not match:
            continue
        parent_indent = len(match.group("indent"))
        body: list[str] = []
        for child in lines[index + 1 :]:
            if not child.strip() or child.lstrip().startswith("#"):
                body.append(child)
                continue
            child_indent = len(child) - len(child.lstrip())
            indentless_list = child_indent == parent_indent and child.lstrip().startswith("-")
            if child_indent <= parent_indent and not indentless_list:
                break
            body.append(child)
        return "\n".join(body), parent_indent
    return None


def yaml_section_at_indent(
    text: str, key: str, indent: int
) -> tuple[str, int] | None:
    lines = text.splitlines()
    for index, line in enumerate(lines):
        match = re.fullmatch(
            rf"(?P<indent> {{{indent}}}){re.escape(key)}:\s*(?:#.*)?",
            line,
        )
        if not match:
            continue
        body: list[str] = []
        for child in lines[index + 1 :]:
            if not child.strip() or child.lstrip().startswith("#"):
                body.append(child)
                continue
            child_indent = len(child) - len(child.lstrip())
            indentless_list = (
                child_indent == indent and child.lstrip().startswith("-")
            )
            if child_indent <= indent and not indentless_list:
                break
            body.append(child)
        return "\n".join(body), indent
    return None


def direct_child_indent(body: str, parent_indent: int) -> int | None:
    candidates = []
    for line in body.splitlines():
        if not line.strip() or line.lstrip().startswith(("#", "-")):
            continue
        indent = len(line) - len(line.lstrip())
        if indent > parent_indent:
            candidates.append(indent)
    return min(candidates, default=None)


def yaml_list_entries(body: str, parent_indent: int) -> list[str]:
    lines = body.splitlines()
    item_indents = [
        len(line) - len(line.lstrip())
        for line in lines
        if line.strip()
        and not line.lstrip().startswith("#")
        and line.lstrip().startswith("-")
        and len(line) - len(line.lstrip()) >= parent_indent
    ]
    if not item_indents:
        return []
    item_indent = min(item_indents)
    starts = [
        index
        for index, line in enumerate(lines)
        if len(line) - len(line.lstrip()) == item_indent
        and line.lstrip().startswith("-")
    ]
    entries: list[str] = []
    for position, start in enumerate(starts):
        end = starts[position + 1] if position + 1 < len(starts) else len(lines)
        first = lines[start].lstrip()[1:].lstrip()
        remaining = lines[start + 1 : end]
        direct_indent = min(
            (
                len(line) - len(line.lstrip())
                for line in remaining
                if line.strip()
                and not line.lstrip().startswith(("#", "-"))
                and len(line) - len(line.lstrip()) > item_indent
            ),
            default=None,
        )
        entry = [first] if first else []
        if direct_indent is not None:
            for line in remaining:
                if not line.strip():
                    entry.append("")
                    continue
                indentation = len(line) - len(line.lstrip())
                if indentation >= direct_indent:
                    entry.append(line[direct_indent:])
        entries.append("\n".join(entry))
    return entries


def yaml_scalar_values_at_indent(
    text: str, key: str, indent: int
) -> list[str]:
    values: list[str] = []
    for line in text.splitlines():
        if len(line) - len(line.lstrip()) != indent:
            continue
        value = yaml_input_scalar(line[indent:], key, indent=0)
        if value is not None:
            values.append(value)
    return values


def yaml_list_item_scalar_values(
    body: str, parent_indent: int, key: str
) -> list[str]:
    return [
        value
        for entry in yaml_list_entries(body, parent_indent)
        for value in yaml_scalar_values_at_indent(entry, key, 0)
    ]


def is_scoped_otel_environment_name(name: str) -> bool:
    return (
        name == "OTEL_SERVICE_NAME"
        or name.startswith("OTEL_EXPORTER_")
        or name.startswith("SPLUNK_")
    )


def validate_existing_otel_environment(
    container_entry: str, expected: dict[str, str]
) -> None:
    env_result = yaml_section_at_indent(container_entry, "env", 0)
    if not env_result:
        inline_env = yaml_input_scalar(container_entry, "env", indent=0)
        if inline_env not in (None, "", "[]", "null", "~"):
            raise ValueError(OTEL_ENV_CONFLICT_ERROR)
        return

    env, env_indent = env_result
    seen: set[str] = set()
    for entry in yaml_list_entries(env, env_indent):
        if entry.lstrip().startswith("{"):
            raise ValueError(OTEL_ENV_CONFLICT_ERROR)
        names = yaml_scalar_values_at_indent(entry, "name", 0)
        scoped_names = [
            name for name in names if is_scoped_otel_environment_name(name)
        ]
        if not scoped_names:
            continue
        if len(names) != 1 or len(scoped_names) != 1:
            raise ValueError(OTEL_ENV_CONFLICT_ERROR)

        name = scoped_names[0]
        if name in seen:
            raise ValueError(OTEL_ENV_CONFLICT_ERROR)
        seen.add(name)

        if (
            name not in expected
            or yaml_input_scalar(entry, "valueFrom", indent=0) is not None
        ):
            raise ValueError(OTEL_ENV_CONFLICT_ERROR)
        values = yaml_scalar_values_at_indent(entry, "value", 0)
        if len(values) != 1:
            raise ValueError(OTEL_ENV_CONFLICT_ERROR)
        value = values[0]
        if (
            value != expected[name]
            or "$(" in value
            or "${" in value
        ):
            raise ValueError(OTEL_ENV_CONFLICT_ERROR)


def yaml_list_scalar_values(body: str, parent_indent: int) -> list[str]:
    lines = body.splitlines()
    item_indents = [
        len(line) - len(line.lstrip())
        for line in lines
        if line.strip()
        and not line.lstrip().startswith("#")
        and line.lstrip().startswith("-")
        and len(line) - len(line.lstrip()) >= parent_indent
    ]
    if not item_indents:
        return []
    item_indent = min(item_indents)
    values: list[str] = []
    for line in lines:
        if len(line) - len(line.lstrip()) != item_indent:
            continue
        stripped = line.lstrip()
        if not stripped.startswith("-"):
            continue
        value = re.sub(r"\s+#.*$", "", stripped[1:].strip()).strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        if value:
            values.append(value)
    return values


def kustomization_file(directory: Path) -> Path:
    for name in KUSTOMIZATION_NAMES:
        candidate = directory / name
        if candidate.is_file():
            return candidate
    raise ValueError("base directory has no Kustomization file")


def kustomization_references(text: str) -> list[str]:
    references: list[str] = []
    for key in ("resources", "components", "bases"):
        section = yaml_section_at_indent(text, key, 0)
        if section:
            body, indent = section
            references.extend(yaml_list_scalar_values(body, indent))
            continue
        inline = yaml_input_scalar(text, key, indent=0)
        if not inline:
            continue
        if not inline.startswith("[") or not inline.endswith("]"):
            raise ValueError(
                "Kustomization resource references must use a YAML list"
            )
        for value in inline[1:-1].split(","):
            value = value.strip()
            if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
                value = value[1:-1]
            if value:
                references.append(value)
    return references


def validate_local_kustomization_graph(
    directory: Path,
    *,
    allowed_root: Path,
    visited: set[Path] | None = None,
) -> None:
    seen = visited if visited is not None else set()
    resolved_directory = directory.resolve(strict=True)
    if resolved_directory in seen:
        return
    seen.add(resolved_directory)
    if not is_within(resolved_directory, allowed_root):
        raise ValueError("Kustomization resource escapes the application root")

    definition = kustomization_file(resolved_directory)
    text = definition.read_text(encoding="utf-8")
    without_comments = "\n".join(
        line.split("#", 1)[0] for line in text.splitlines()
    )
    if REMOTE_KUSTOMIZE_REFERENCE.search(without_comments):
        raise ValueError(
            "remote Kustomization resources are not allowed during generation"
        )

    for reference in kustomization_references(text):
        if REMOTE_KUSTOMIZE_REFERENCE.search(reference):
            raise ValueError(
                "remote Kustomization resources are not allowed during generation"
            )
        child = (resolved_directory / reference).resolve(strict=False)
        if not is_within(child, allowed_root):
            raise ValueError("Kustomization resource escapes the application root")
        if child.is_dir():
            validate_local_kustomization_graph(
                child,
                allowed_root=allowed_root,
                visited=seen,
            )


def base_manifest(base: Path, *, allowed_root: Path) -> str:
    if base.is_file():
        return base.read_text(encoding="utf-8")

    validate_local_kustomization_graph(base, allowed_root=allowed_root)
    kubectl = shutil.which("kubectl")
    if not kubectl:
        raise ValueError(
            "kubectl is required to inspect a Kustomization base directory"
        )
    try:
        result = subprocess.run(
            [kubectl, "kustomize", str(base)],
            cwd=base,
            text=True,
            capture_output=True,
            check=False,
            timeout=KUSTOMIZE_TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired:
        raise ValueError(
            "base Kustomization render timed out after "
            f"{KUSTOMIZE_TIMEOUT_SECONDS} seconds"
        ) from None
    if result.returncode:
        raise ValueError(
            "cannot render base Kustomization with kubectl "
            f"(exit {result.returncode})"
        )
    if not result.stdout.strip():
        raise ValueError("base Kustomization rendered no Kubernetes resources")
    return result.stdout


def validate_base_target(
    base: Path,
    *,
    allowed_root: Path,
    workload_kind: str,
    workload_name: str,
    namespace: str,
    container: str,
    expected_environment: dict[str, str],
) -> None:
    selected_container_entries: list[list[str]] = []
    manifest = base_manifest(base, allowed_root=allowed_root)
    for document in YAML_DOCUMENT_BOUNDARY.split(manifest):
        if yaml_input_scalar(document, "apiVersion", indent=0) != "apps/v1":
            continue
        if yaml_input_scalar(document, "kind", indent=0) != workload_kind:
            continue

        metadata_result = yaml_section_at_indent(document, "metadata", 0)
        spec_result = yaml_section_at_indent(document, "spec", 0)
        if not metadata_result or not spec_result:
            continue
        metadata, metadata_indent = metadata_result
        metadata_child_indent = direct_child_indent(metadata, metadata_indent)
        if metadata_child_indent is None:
            continue
        rendered_name = yaml_input_scalar(
            metadata, "name", indent=metadata_child_indent
        )
        rendered_namespace = (
            yaml_input_scalar(
                metadata, "namespace", indent=metadata_child_indent
            )
            or "default"
        )
        if rendered_name != workload_name or rendered_namespace != namespace:
            continue

        spec, spec_indent = spec_result
        spec_child_indent = direct_child_indent(spec, spec_indent)
        template_result = (
            yaml_section_at_indent(spec, "template", spec_child_indent)
            if spec_child_indent is not None
            else None
        )
        if not template_result:
            selected_container_entries.append([])
            continue
        template, template_indent = template_result
        template_child_indent = direct_child_indent(template, template_indent)
        pod_spec_result = (
            yaml_section_at_indent(template, "spec", template_child_indent)
            if template_child_indent is not None
            else None
        )
        if not pod_spec_result:
            selected_container_entries.append([])
            continue
        pod_spec, pod_spec_indent = pod_spec_result
        pod_spec_child_indent = direct_child_indent(pod_spec, pod_spec_indent)
        containers_result = (
            yaml_section_at_indent(
                pod_spec, "containers", pod_spec_child_indent
            )
            if pod_spec_child_indent is not None
            else None
        )
        if not containers_result:
            selected_container_entries.append([])
            continue
        containers, containers_indent = containers_result
        matching_entries: list[str] = []
        for entry in yaml_list_entries(containers, containers_indent):
            names = yaml_scalar_values_at_indent(entry, "name", 0)
            matching_entries.extend([entry] * names.count(container))
        selected_container_entries.append(matching_entries)

    if len(selected_container_entries) != 1:
        raise ValueError(
            "base must contain exactly one selected workload: "
            f"apps/v1 {workload_kind}/{workload_name} in namespace "
            f"{namespace!r}; found {len(selected_container_entries)}"
        )
    if len(selected_container_entries[0]) != 1:
        raise ValueError(
            "selected workload must contain exactly one target container: "
            f"{container!r}; found {len(selected_container_entries[0])}"
        )
    validate_existing_otel_environment(
        selected_container_entries[0][0], expected_environment
    )


def matching_service_routes(
    text: str,
    *,
    service: str,
    namespace: str,
    port_name: str,
    port: int,
) -> tuple[int, bool]:
    matching_services = 0
    duplicate_ports = False
    for document in YAML_DOCUMENT_BOUNDARY.split(text):
        if yaml_input_scalar(document, "kind", indent=0) != "Service":
            continue
        metadata_result = yaml_section(document, "metadata")
        spec_result = yaml_section(document, "spec")
        if not metadata_result or not spec_result:
            continue
        metadata, metadata_indent = metadata_result
        metadata_child_indent = direct_child_indent(metadata, metadata_indent)
        if metadata_child_indent is None:
            continue
        if yaml_input_scalar(metadata, "name", indent=metadata_child_indent) != service:
            continue
        if (
            yaml_input_scalar(metadata, "namespace", indent=metadata_child_indent)
            != namespace
        ):
            continue
        spec, _ = spec_result
        ports_result = yaml_section(spec, "ports")
        if not ports_result:
            continue
        ports, _ = ports_result
        entries = re.split(r"^\s*-\s*", ports, flags=re.MULTILINE)[1:]
        matching_ports = 0
        for entry in entries:
            if yaml_input_scalar(entry, "name") != port_name:
                continue
            rendered_port = yaml_input_scalar(entry, "port")
            if rendered_port == str(port):
                matching_ports += 1
        if matching_ports == 1:
            matching_services += 1
        elif matching_ports > 1:
            duplicate_ports = True
    return matching_services, duplicate_ports


def validate_collector_evidence(
    path: Path,
    *,
    service: str,
    namespace: str,
    port_name: str,
    port: int,
) -> str:
    try:
        evidence_bytes = path.read_bytes()
        text = evidence_bytes.decode("utf-8")
    except (OSError, UnicodeError) as exc:
        raise ValueError(f"cannot read collector evidence {path}: {exc}") from exc
    matching_services, duplicate_ports = matching_service_routes(
        text,
        service=service,
        namespace=namespace,
        port_name=port_name,
        port=port,
    )
    if matching_services != 1 or duplicate_ports:
        raise ValueError(
            "collector evidence must contain exactly one selected Service route: "
            f"Service {service!r} in namespace {namespace!r} with "
            f"port {port_name!r}={port}"
        )
    return hashlib.sha256(evidence_bytes).hexdigest()


def normalized_inputs(args: argparse.Namespace) -> dict[str, Any]:
    invocation = Path.cwd().resolve()
    workspace = (
        resolve_from(args.workspace_root, invocation, strict=True)
        if args.workspace_root
        else find_workspace_root(invocation)
    )
    if not workspace.is_dir():
        raise ValueError(f"workspace root is not a directory: {workspace}")

    app = resolve_from(args.app, invocation, strict=True)
    if not app.is_dir():
        raise ValueError(f"application path is not a directory: {app}")
    if not is_within(app, workspace):
        raise ValueError(f"application path escapes workspace root: {app}")

    output_input = (
        args.output if args.output is not None else Path("deploy/otel-config")
    )
    raw_output = (
        output_input if output_input.is_absolute() else invocation / output_input
    )
    if args.output is None:
        raw_output = app / output_input
    raw_output = Path(os.path.abspath(raw_output))
    output = raw_output.resolve(strict=False)
    if not is_within(output, app):
        raise ValueError(
            f"output path must remain inside application root: {output}"
        )
    reject_symlink_components(raw_output, app)

    if args.scaffold_workload and args.base is not None:
        raise ValueError("--scaffold-workload cannot be combined with --base")
    scaffold_workload = args.scaffold_workload or args.base is None
    base: Path | None = None
    if args.base is not None:
        base = resolve_from(args.base, app, strict=True)
        if not is_within(base, app):
            raise ValueError(f"base path escapes application root: {base}")
        if base == output or is_within(base, output):
            raise ValueError("base path must not be inside the generated overlay")
        if not base.is_file() and not base.is_dir():
            raise ValueError(f"base path is not a file or directory: {base}")
        if base.is_dir() and not any(
            (base / name).is_file()
            for name in ("kustomization.yaml", "kustomization.yml", "Kustomization")
        ):
            raise ValueError(f"base directory has no Kustomization file: {base}")

    if not REALM.fullmatch(args.realm):
        raise ValueError(f"invalid realm: {args.realm!r}")
    default_name = dns_label_from_text(app.name, fallback="application")
    if scaffold_workload:
        application_namespace = args.application_namespace or default_name
        workload_name = args.workload_name or default_name
        container = args.container or workload_name
    else:
        if args.image or args.container_port is not None:
            raise ValueError("--image and --container-port are scaffold-only")
        missing = [
            flag
            for flag, value in (
                ("--application-namespace", args.application_namespace),
                ("--workload-name", args.workload_name),
                ("--container", args.container),
            )
            if not value
        ]
        if missing:
            raise ValueError(
                "existing-base mode requires "
                + ", ".join(missing)
                + "; omit --base or pass --scaffold-workload to generate a scaffold"
            )
        application_namespace = args.application_namespace or default_name
        workload_name = args.workload_name or default_name
        container = args.container or workload_name

    image = args.image or f"example.invalid/{workload_name}:replace-at-deploy-time"
    container_port = args.container_port
    if container_port is not None and not 1 <= container_port <= 65535:
        raise ValueError("--container-port must be between 1 and 65535")

    for label, value in (
        ("collector namespace", args.collector_namespace),
        ("collector release", args.collector_release),
        ("application namespace", application_namespace),
        ("workload name", workload_name),
        ("container name", container),
    ):
        validate_dns_label(label, value)
    validate_secret_name(args.secret_name)
    if len(args.collector_release) > COLLECTOR_RELEASE_NAME_MAX_LENGTH:
        raise ValueError(
            "collector release must not exceed "
            f"{COLLECTOR_RELEASE_NAME_MAX_LENGTH} characters"
        )

    service_name = args.service_name or workload_name
    validate_dns_label("OTel service name", service_name)
    default_suffix = "-collector" if args.topology == "gateway" else "-collector-agent"
    collector_service = args.collector_service or f"{args.collector_release}{default_suffix}"
    validate_dns_label("collector Service", collector_service)
    if args.cluster_domain:
        if not DOMAIN.fullmatch(args.cluster_domain):
            raise ValueError(f"invalid cluster domain: {args.cluster_domain!r}")
        cluster_domain = args.cluster_domain.rstrip(".")
    else:
        cluster_domain = ""

    evidence = None
    evidence_sha256 = None
    evidence_path = None
    if args.collector_evidence:
        evidence_path = resolve_from(args.collector_evidence, invocation, strict=True)
        if not is_within(evidence_path, workspace):
            raise ValueError(
                f"collector evidence escapes workspace root: {evidence_path}"
            )
        if not evidence_path.is_file():
            raise ValueError(f"collector evidence is not a file: {evidence_path}")
        evidence = os.path.relpath(evidence_path, app)

    service_resolution = (
        "generated-collector-yaml"
        if evidence
        else "explicit"
        if args.collector_service
        else "release-topology-default"
    )
    port = 4318 if args.protocol == "http/protobuf" else 4317
    port_name = "otlp-http" if args.protocol == "http/protobuf" else "otlp"
    if evidence_path:
        evidence_sha256 = validate_collector_evidence(
            evidence_path,
            service=collector_service,
            namespace=args.collector_namespace,
            port_name=port_name,
            port=port,
        )
    host = f"{collector_service}.{args.collector_namespace}.svc"
    if cluster_domain:
        host = f"{host}.{cluster_domain}"
    endpoint = f"http://{host}:{port}"
    traces_endpoint = (
        f"{endpoint}/v1/traces" if args.protocol == "http/protobuf" else endpoint
    )
    metrics_endpoint = (
        f"{endpoint}/v1/metrics" if args.protocol == "http/protobuf" else endpoint
    )
    otel_environment = {
        "OTEL_SERVICE_NAME": service_name,
        "OTEL_EXPORTER_OTLP_ENDPOINT": endpoint,
        "OTEL_EXPORTER_OTLP_PROTOCOL": args.protocol,
        "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT": traces_endpoint,
        "OTEL_EXPORTER_OTLP_TRACES_PROTOCOL": args.protocol,
        "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT": metrics_endpoint,
        "OTEL_EXPORTER_OTLP_METRICS_PROTOCOL": args.protocol,
    }

    if not scaffold_workload and base is not None:
        validate_base_target(
            base,
            allowed_root=app,
            workload_kind=args.workload_kind,
            workload_name=workload_name,
            namespace=application_namespace,
            container=container,
            expected_environment=otel_environment,
        )

    if scaffold_workload:
        base_from_overlay = SCAFFOLD_WORKLOAD_FILE.name
        base_from_app = os.path.relpath(output / SCAFFOLD_WORKLOAD_FILE, app)
        base_is_kustomization = True
    else:
        assert base is not None
        base_from_overlay = os.path.relpath(base, output / "kubernetes")
        base_from_app = os.path.relpath(base, app)
        base_is_kustomization = base.is_dir()
    app_from_output = os.path.relpath(app, output)
    workspace_from_output = os.path.relpath(workspace, output)
    return {
        "workspace": workspace,
        "app": app,
        "output": output,
        "base": base,
        "base_from_overlay": Path(base_from_overlay).as_posix(),
        "base_from_app": Path(base_from_app).as_posix(),
        "app_from_output": Path(app_from_output).as_posix(),
        "workspace_from_output": Path(workspace_from_output).as_posix(),
        "base_is_kustomization": base_is_kustomization,
        "scaffold_workload": scaffold_workload,
        "platform": args.platform,
        "realm": args.realm,
        "collector_namespace": args.collector_namespace,
        "collector_release": args.collector_release,
        "collector_service": collector_service,
        "collector_evidence": evidence,
        "collector_evidence_sha256": evidence_sha256,
        "service_resolution": service_resolution,
        "topology": args.topology,
        "secret_name": args.secret_name,
        "cluster_domain": cluster_domain,
        "protocol": args.protocol,
        "port": port,
        "port_name": port_name,
        "endpoint": endpoint,
        "traces_endpoint": traces_endpoint,
        "metrics_endpoint": metrics_endpoint,
        "otel_environment": otel_environment,
        "application_namespace": application_namespace,
        "workload_api_version": "apps/v1",
        "workload_kind": args.workload_kind,
        "workload_name": workload_name,
        "container": container,
        "image": image,
        "container_port": container_port,
        "service_name": service_name,
    }


def hash_inputs(values: dict[str, Any]) -> str:
    excluded = {"workspace", "app", "output", "base"}
    stable = {key: value for key, value in values.items() if key not in excluded}
    payload = json.dumps(stable, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def yaml_key(value: str) -> str:
    return value if YAML_KEY.fullmatch(value) else json.dumps(value)


def yaml_scalar(value: Any) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value)
    raise TypeError(f"unsupported YAML scalar: {type(value).__name__}")


def yaml_lines(value: Any, indent: int = 0) -> list[str]:
    prefix = " " * indent
    if isinstance(value, dict):
        result: list[str] = []
        for key, item in value.items():
            rendered_key = yaml_key(str(key))
            if isinstance(item, (dict, list)):
                result.append(f"{prefix}{rendered_key}:")
                result.extend(yaml_lines(item, indent + 2))
            else:
                result.append(f"{prefix}{rendered_key}: {yaml_scalar(item)}")
        return result
    if isinstance(value, list):
        result = []
        for item in value:
            if isinstance(item, (dict, list)):
                result.append(f"{prefix}-")
                result.extend(yaml_lines(item, indent + 2))
            else:
                result.append(f"{prefix}- {yaml_scalar(item)}")
        return result
    return [f"{prefix}{yaml_scalar(value)}"]


def render_yaml(document: dict[str, Any], input_hash: str) -> str:
    return (
        f"{OWNER_MARKER}\n{HASH_PREFIX}{input_hash}\n"
        + "\n".join(yaml_lines(document))
        + "\n"
    )


def documents(values: dict[str, Any], input_hash: str) -> dict[Path, str]:
    evidence: dict[str, Any] = {
        "serviceResolution": values["service_resolution"],
        "liveRoute": "unverified",
    }
    if values["collector_evidence"]:
        evidence["source"] = values["collector_evidence"]
        evidence["sha256"] = values["collector_evidence_sha256"]

    contract = {
        "schemaVersion": 1,
        "kind": "otel-connection",
        "generator": {
            "name": GENERATOR_NAME,
            "version": GENERATOR_VERSION,
        },
        "platform": values["platform"],
        "application": {
            "root": values["app_from_output"],
            "workspaceRoot": values["workspace_from_output"],
            "base": values["base_from_app"],
            "overlayMode": (
                "scaffold"
                if values["scaffold_workload"]
                else "standalone"
                if values["base_is_kustomization"]
                else "component"
            ),
            "serviceName": values["service_name"],
            "workload": {
                "apiVersion": values["workload_api_version"],
                "kind": values["workload_kind"],
                "name": values["workload_name"],
                "namespace": values["application_namespace"],
                "container": values["container"],
            },
        },
        "collector": {
            "topology": values["topology"],
            "release": values["collector_release"],
            "namespace": values["collector_namespace"],
            "service": values["collector_service"],
            "secretRef": {
                "name": values["secret_name"],
                "namespace": values["collector_namespace"],
                "key": "splunk_observability_access_token",
                "usage": "collector-egress-only",
            },
        },
        "splunkObservability": {"realm": values["realm"]},
        "otlp": {
            "protocol": values["protocol"],
            "port": values["port"],
            "portName": values["port_name"],
            "endpoint": values["endpoint"],
            "tracesEndpoint": values["traces_endpoint"],
            "metricsEndpoint": values["metrics_endpoint"],
            "tls": {"mode": "plaintext-cluster-local"},
            "authentication": {"mode": "none"},
        },
        "verification": evidence,
    }

    env = [
        {"name": name, "value": value}
        for name, value in values["otel_environment"].items()
    ]
    patch = {
        "apiVersion": values["workload_api_version"],
        "kind": values["workload_kind"],
        "metadata": {
            "name": values["workload_name"],
            "namespace": values["application_namespace"],
        },
        "spec": {
            "template": {
                "metadata": {
                    "annotations": {
                        "obstudio.splunk.com/otel-generate-app-collector-config-input": input_hash
                    }
                },
                "spec": {
                    "containers": [
                        {"name": values["container"], "env": env}
                    ]
                },
            }
        },
    }
    kustomization: dict[str, Any] = {
        "apiVersion": (
            "kustomize.config.k8s.io/v1beta1"
            if values["base_is_kustomization"]
            else "kustomize.config.k8s.io/v1alpha1"
        ),
        "kind": (
            "Kustomization" if values["base_is_kustomization"] else "Component"
        ),
        "patches": [
            {
                "path": "otel-env-patch.yaml",
                "target": {
                    "group": "apps",
                    "version": "v1",
                    "kind": values["workload_kind"],
                    "name": values["workload_name"],
                    "namespace": values["application_namespace"],
                },
            }
        ],
    }
    if values["base_is_kustomization"]:
        kustomization["resources"] = [values["base_from_overlay"]]

    rendered = {
        MANAGED_FILES[0]: render_yaml(contract, input_hash),
        MANAGED_FILES[1]: render_yaml(kustomization, input_hash),
        MANAGED_FILES[2]: render_yaml(patch, input_hash),
    }
    if values["scaffold_workload"]:
        labels = {"app.kubernetes.io/name": values["service_name"]}
        container: dict[str, Any] = {
            "name": values["container"],
            "image": values["image"],
        }
        if values["container_port"] is not None:
            container["ports"] = [
                {
                    "name": "http",
                    "containerPort": values["container_port"],
                    "protocol": "TCP",
                }
            ]
        workload_spec: dict[str, Any] = {
            "selector": {"matchLabels": labels},
            "template": {
                "metadata": {
                    "labels": labels,
                    "annotations": {
                        "obstudio.splunk.com/otel-generate-app-collector-config-input": input_hash
                    },
                },
                "spec": {"containers": [container]},
            },
        }
        if values["workload_kind"] in {"Deployment", "StatefulSet"}:
            workload_spec["replicas"] = 1
        if values["workload_kind"] == "StatefulSet":
            workload_spec["serviceName"] = values["service_name"]

        workload = {
            "apiVersion": values["workload_api_version"],
            "kind": values["workload_kind"],
            "metadata": {
                "name": values["workload_name"],
                "namespace": values["application_namespace"],
                "annotations": {
                    "obstudio.splunk.com/scaffold": "true",
                    "obstudio.splunk.com/review-required": (
                        "image, resources, probes, service account, "
                        "secrets, and rollout settings"
                    ),
                },
            },
            "spec": workload_spec,
        }
        rendered[SCAFFOLD_WORKLOAD_FILE] = render_yaml(workload, input_hash)
    return rendered


def atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp_name, path)
    except BaseException:
        try:
            os.unlink(temp_name)
        except FileNotFoundError:
            pass
        raise


def write_documents(
    output: Path, rendered: dict[Path, str], *, overwrite: bool
) -> tuple[list[Path], bool]:
    if output.exists() and not output.is_dir():
        raise ValueError(f"output path is not a directory: {output}")
    destinations = {output / relative: text for relative, text in rendered.items()}

    for path in destinations:
        reject_symlink_components(path, output)

    stale_scaffold = output / SCAFFOLD_WORKLOAD_FILE
    stale_scaffold_cleanup = False
    if stale_scaffold not in destinations and (
        stale_scaffold.exists() or stale_scaffold.is_symlink()
    ):
        reject_symlink_components(stale_scaffold, output)
        if not stale_scaffold.is_file():
            raise ValueError(
                f"stale scaffold output is not a regular file: {stale_scaffold}"
            )
        existing = stale_scaffold.read_text(encoding="utf-8")
        if not existing.startswith(MANAGED_PREFIXES):
            raise ValueError(
                "refusing to remove hand-authored stale scaffold file: "
                f"{stale_scaffold}"
            )
        if not overwrite:
            raise ValueError(
                "stale generated scaffold remains; review changes and use "
                f"--overwrite: {stale_scaffold}"
            )
        stale_scaffold_cleanup = True

    unchanged = all(
        path.is_file() and path.read_text(encoding="utf-8") == text
        for path, text in destinations.items()
    )
    if unchanged and not stale_scaffold_cleanup:
        return list(destinations), True

    for path in destinations:
        if path.exists() and not path.is_file():
            raise ValueError(f"managed output is not a regular file: {path}")
        if path.exists():
            existing = path.read_text(encoding="utf-8")
            if not existing.startswith(MANAGED_PREFIXES):
                raise ValueError(f"refusing to overwrite hand-authored file: {path}")
            if not overwrite:
                raise ValueError(
                    f"managed file differs; review changes and use --overwrite: {path}"
                )

    for path, text in destinations.items():
        atomic_write(path, text)
    if stale_scaffold_cleanup:
        stale_scaffold.unlink()
    return list(destinations), False


def generate(args: argparse.Namespace) -> tuple[dict[str, Any], list[Path], bool]:
    values = normalized_inputs(args)
    input_hash = hash_inputs(values)
    rendered = documents(values, input_hash)
    written, unchanged = write_documents(
        values["output"], rendered, overwrite=args.overwrite
    )
    return values, written, unchanged


def shell_quote(value: object) -> str:
    return shlex.quote(str(value))


def print_next_commands(values: dict[str, Any]) -> None:
    overlay = values["output"] / "kubernetes"

    print()
    print("Next commands:")

    if values["base_is_kustomization"]:
        print("# 1. Render the generated application config")
        print(f"kubectl kustomize {shell_quote(overlay)}")
        if values["scaffold_workload"]:
            print()
            print("# 2. Review the workload scaffold before deploying")
            print(
                "# Replace the image, resources, probes, service account, "
                "secrets, and rollout settings first."
            )
            if "replace-at-deploy-time" in values["image"]:
                workload = overlay / SCAFFOLD_WORKLOAD_FILE.name
                print(
                    "# Placeholder image is still present in "
                    f"{shell_quote(workload)}"
                )
            print("# After review, deploy the application config")
        else:
            print()
            print("# 2. Deploy the application config")
        print(f"kubectl apply -k {shell_quote(overlay)}")
    else:
        component_from_app = Path(os.path.relpath(overlay, values["app"])).as_posix()
        print("# 1. Add the generated component to your app Kustomization")
        print(
            "# Use a path relative to that Kustomization file; adjust this "
            "app-root-relative path if needed."
        )
        print("components:")
        print(f"  - {json.dumps(component_from_app)}")
        print(f"# Generated component directory: {shell_quote(overlay)}")
        print("# 2. Render/deploy the Kustomization that includes this component.")


def main(argv: list[str] | None = None) -> int:
    try:
        args = parse_args(argv)
        values, written, unchanged = generate(args)
    except (OSError, UnicodeError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    action = "Unchanged" if unchanged else "Generated"
    print(f"{action} OTel application configuration: {values['app']}")
    print(
        "Target: "
        f"{values['workload_kind']}/{values['workload_name']} "
        f"container {values['container']}"
    )
    print(f"Collector endpoint: {values['endpoint']}")
    print(f"Service resolution: {values['service_resolution']}")
    for path in written:
        print(path)
    print("No access token was read or written.")
    print("Live Collector Service readiness remains unverified.")
    print_next_commands(values)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
