// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.19.1
// source: opentelemetry/proto/collector/profiles/v1development/profiles_service.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ProfilesDictionary, ResourceProfiles } from "../../../profiles/v1development/profiles.js";
function createBaseExportProfilesServiceRequest() {
    return { resourceProfiles: [], dictionary: undefined };
}
export const ExportProfilesServiceRequest = {
    encode(message, writer = new BinaryWriter()) {
        for (const v of message.resourceProfiles) {
            ResourceProfiles.encode(v, writer.uint32(10).fork()).join();
        }
        if (message.dictionary !== undefined) {
            ProfilesDictionary.encode(message.dictionary, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseExportProfilesServiceRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.resourceProfiles.push(ResourceProfiles.decode(reader, reader.uint32()));
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.dictionary = ProfilesDictionary.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            resourceProfiles: globalThis.Array.isArray(object?.resourceProfiles)
                ? object.resourceProfiles.map((e) => ResourceProfiles.fromJSON(e))
                : globalThis.Array.isArray(object?.resource_profiles)
                    ? object.resource_profiles.map((e) => ResourceProfiles.fromJSON(e))
                    : [],
            dictionary: isSet(object.dictionary) ? ProfilesDictionary.fromJSON(object.dictionary) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.resourceProfiles?.length) {
            obj.resourceProfiles = message.resourceProfiles.map((e) => ResourceProfiles.toJSON(e));
        }
        if (message.dictionary !== undefined) {
            obj.dictionary = ProfilesDictionary.toJSON(message.dictionary);
        }
        return obj;
    },
    create(base) {
        return ExportProfilesServiceRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseExportProfilesServiceRequest();
        message.resourceProfiles = object.resourceProfiles?.map((e) => ResourceProfiles.fromPartial(e)) || [];
        message.dictionary = (object.dictionary !== undefined && object.dictionary !== null)
            ? ProfilesDictionary.fromPartial(object.dictionary)
            : undefined;
        return message;
    },
};
function createBaseExportProfilesServiceResponse() {
    return { partialSuccess: undefined };
}
export const ExportProfilesServiceResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.partialSuccess !== undefined) {
            ExportProfilesPartialSuccess.encode(message.partialSuccess, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseExportProfilesServiceResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.partialSuccess = ExportProfilesPartialSuccess.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            partialSuccess: isSet(object.partialSuccess)
                ? ExportProfilesPartialSuccess.fromJSON(object.partialSuccess)
                : isSet(object.partial_success)
                    ? ExportProfilesPartialSuccess.fromJSON(object.partial_success)
                    : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.partialSuccess !== undefined) {
            obj.partialSuccess = ExportProfilesPartialSuccess.toJSON(message.partialSuccess);
        }
        return obj;
    },
    create(base) {
        return ExportProfilesServiceResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseExportProfilesServiceResponse();
        message.partialSuccess = (object.partialSuccess !== undefined && object.partialSuccess !== null)
            ? ExportProfilesPartialSuccess.fromPartial(object.partialSuccess)
            : undefined;
        return message;
    },
};
function createBaseExportProfilesPartialSuccess() {
    return { rejectedProfiles: "0", errorMessage: "" };
}
export const ExportProfilesPartialSuccess = {
    encode(message, writer = new BinaryWriter()) {
        if (message.rejectedProfiles !== "0") {
            writer.uint32(8).int64(message.rejectedProfiles);
        }
        if (message.errorMessage !== "") {
            writer.uint32(18).string(message.errorMessage);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseExportProfilesPartialSuccess();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.rejectedProfiles = reader.int64().toString();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.errorMessage = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            rejectedProfiles: isSet(object.rejectedProfiles)
                ? globalThis.String(object.rejectedProfiles)
                : isSet(object.rejected_profiles)
                    ? globalThis.String(object.rejected_profiles)
                    : "0",
            errorMessage: isSet(object.errorMessage)
                ? globalThis.String(object.errorMessage)
                : isSet(object.error_message)
                    ? globalThis.String(object.error_message)
                    : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.rejectedProfiles !== "0") {
            obj.rejectedProfiles = message.rejectedProfiles;
        }
        if (message.errorMessage !== "") {
            obj.errorMessage = message.errorMessage;
        }
        return obj;
    },
    create(base) {
        return ExportProfilesPartialSuccess.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseExportProfilesPartialSuccess();
        message.rejectedProfiles = object.rejectedProfiles ?? "0";
        message.errorMessage = object.errorMessage ?? "";
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
