version: 2

project_name: obstudio

builds:
  - dir: observer
    main: ./cmd/obstudio
    binary: obstudio
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats:
      - zip
    files:
      - docs/USER.md
      - docs/examples.md

release:
  github:
    owner: signalfx
    name: obstudio

changelog:
  sort: asc
