name: customer-python
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - click>=8.1
      - fastapi>=0.115
      - gunicorn>=23
      - opentelemetry-distro>=0.59b0
      - opentelemetry-exporter-otlp>=1.38
      - opentelemetry-instrumentation-fastapi>=0.59b0
      - uvicorn-worker>=0.3
      - uvicorn[standard]>=0.34
