// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.19.1
// source: opentelemetry/proto/resource/v1/resource.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { EntityRef, KeyValue } from "../../common/v1/common.js";
function createBaseResource() {
    return { attributes: [], droppedAttributesCount: 0, entityRefs: [] };
}
export const Resource = {
    encode(message, writer = new BinaryWriter()) {
        for (const v of message.attributes) {
            KeyValue.encode(v, writer.uint32(10).fork()).join();
        }
        if (message.droppedAttributesCount !== 0) {
            writer.uint32(16).uint32(message.droppedAttributesCount);
        }
        for (const v of message.entityRefs) {
            EntityRef.encode(v, writer.uint32(26).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseResource();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.attributes.push(KeyValue.decode(reader, reader.uint32()));
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.droppedAttributesCount = reader.uint32();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.entityRefs.push(EntityRef.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            attributes: globalThis.Array.isArray(object?.attributes)
                ? object.attributes.map((e) => KeyValue.fromJSON(e))
                : [],
            droppedAttributesCount: isSet(object.droppedAttributesCount)
                ? globalThis.Number(object.droppedAttributesCount)
                : isSet(object.dropped_attributes_count)
                    ? globalThis.Number(object.dropped_attributes_count)
                    : 0,
            entityRefs: globalThis.Array.isArray(object?.entityRefs)
                ? object.entityRefs.map((e) => EntityRef.fromJSON(e))
                : globalThis.Array.isArray(object?.entity_refs)
                    ? object.entity_refs.map((e) => EntityRef.fromJSON(e))
                    : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.attributes?.length) {
            obj.attributes = message.attributes.map((e) => KeyValue.toJSON(e));
        }
        if (message.droppedAttributesCount !== 0) {
            obj.droppedAttributesCount = Math.round(message.droppedAttributesCount);
        }
        if (message.entityRefs?.length) {
            obj.entityRefs = message.entityRefs.map((e) => EntityRef.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return Resource.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseResource();
        message.attributes = object.attributes?.map((e) => KeyValue.fromPartial(e)) || [];
        message.droppedAttributesCount = object.droppedAttributesCount ?? 0;
        message.entityRefs = object.entityRefs?.map((e) => EntityRef.fromPartial(e)) || [];
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
