// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.19.1
// source: opentelemetry/proto/collector/metrics/v1/metrics_service.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ResourceMetrics } from "../../../metrics/v1/metrics.js";
function createBaseExportMetricsServiceRequest() {
    return { resourceMetrics: [] };
}
export const ExportMetricsServiceRequest = {
    encode(message, writer = new BinaryWriter()) {
        for (const v of message.resourceMetrics) {
            ResourceMetrics.encode(v, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseExportMetricsServiceRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.resourceMetrics.push(ResourceMetrics.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            resourceMetrics: globalThis.Array.isArray(object?.resourceMetrics)
                ? object.resourceMetrics.map((e) => ResourceMetrics.fromJSON(e))
                : globalThis.Array.isArray(object?.resource_metrics)
                    ? object.resource_metrics.map((e) => ResourceMetrics.fromJSON(e))
                    : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.resourceMetrics?.length) {
            obj.resourceMetrics = message.resourceMetrics.map((e) => ResourceMetrics.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return ExportMetricsServiceRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseExportMetricsServiceRequest();
        message.resourceMetrics = object.resourceMetrics?.map((e) => ResourceMetrics.fromPartial(e)) || [];
        return message;
    },
};
function createBaseExportMetricsServiceResponse() {
    return { partialSuccess: undefined };
}
export const ExportMetricsServiceResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.partialSuccess !== undefined) {
            ExportMetricsPartialSuccess.encode(message.partialSuccess, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseExportMetricsServiceResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.partialSuccess = ExportMetricsPartialSuccess.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            partialSuccess: isSet(object.partialSuccess)
                ? ExportMetricsPartialSuccess.fromJSON(object.partialSuccess)
                : isSet(object.partial_success)
                    ? ExportMetricsPartialSuccess.fromJSON(object.partial_success)
                    : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.partialSuccess !== undefined) {
            obj.partialSuccess = ExportMetricsPartialSuccess.toJSON(message.partialSuccess);
        }
        return obj;
    },
    create(base) {
        return ExportMetricsServiceResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseExportMetricsServiceResponse();
        message.partialSuccess = (object.partialSuccess !== undefined && object.partialSuccess !== null)
            ? ExportMetricsPartialSuccess.fromPartial(object.partialSuccess)
            : undefined;
        return message;
    },
};
function createBaseExportMetricsPartialSuccess() {
    return { rejectedDataPoints: "0", errorMessage: "" };
}
export const ExportMetricsPartialSuccess = {
    encode(message, writer = new BinaryWriter()) {
        if (message.rejectedDataPoints !== "0") {
            writer.uint32(8).int64(message.rejectedDataPoints);
        }
        if (message.errorMessage !== "") {
            writer.uint32(18).string(message.errorMessage);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseExportMetricsPartialSuccess();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.rejectedDataPoints = reader.int64().toString();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.errorMessage = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            rejectedDataPoints: isSet(object.rejectedDataPoints)
                ? globalThis.String(object.rejectedDataPoints)
                : isSet(object.rejected_data_points)
                    ? globalThis.String(object.rejected_data_points)
                    : "0",
            errorMessage: isSet(object.errorMessage)
                ? globalThis.String(object.errorMessage)
                : isSet(object.error_message)
                    ? globalThis.String(object.error_message)
                    : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.rejectedDataPoints !== "0") {
            obj.rejectedDataPoints = message.rejectedDataPoints;
        }
        if (message.errorMessage !== "") {
            obj.errorMessage = message.errorMessage;
        }
        return obj;
    },
    create(base) {
        return ExportMetricsPartialSuccess.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseExportMetricsPartialSuccess();
        message.rejectedDataPoints = object.rejectedDataPoints ?? "0";
        message.errorMessage = object.errorMessage ?? "";
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
