#!/usr/bin/env python3
"""Statically validate an OTel application contract and overlay."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlsplit

from validate_collector import (
    direct_child_indent,
    duplicate_yaml_mapping_keys,
    split_yaml_documents,
    yaml_mapping_entry,
    yaml_scalar,
    yaml_section,
)


GENERATOR_NAME = "otel-generate-app-collector-config"
LEGACY_GENERATOR_NAME = "otel-generate-config"
OWNER_MARKER = f"# Generated by {GENERATOR_NAME}. Do not edit."
LEGACY_OWNER_MARKER = f"# Generated by {LEGACY_GENERATOR_NAME}. Do not edit."
OWNER_MARKERS = (OWNER_MARKER, LEGACY_OWNER_MARKER)
HASH = re.compile(
    r"^# (?:otel-generate-app-collector-config|otel-generate-config)"
    r"-input-sha256: ([0-9a-f]{64})$",
    re.MULTILINE,
)
REQUIRED_FILES = (
    Path("otel-connection.yaml"),
    Path("kubernetes/kustomization.yaml"),
    Path("kubernetes/otel-env-patch.yaml"),
)
SCAFFOLD_WORKLOAD_FILE = Path("kubernetes/workload.yaml")
FORBIDDEN_OVERLAY = (
    "splunk_observability_access_token",
    "X-SF-Token",
    "SPLUNK_ACCESS_TOKEN",
    "SPLUNK_REALM",
    "accessToken",
    "secretKeyRef",
    "existingSecret",
    "splunkObservability",
    "insecure_skip_verify",
)
DNS_LABEL = re.compile(r"^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")
DNS_SUBDOMAIN = re.compile(
    r"^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)*"
    r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$"
)


@dataclass(frozen=True)
class WorkloadIdentity:
    api_version: str
    kind: str
    name: str
    namespace: str
    container: str


def single_yaml_document(
    text: str,
    *,
    label: str,
    errors: list[str],
) -> str:
    documents = split_yaml_documents(text)
    if len(documents) != 1:
        errors.append(f"{label} must contain exactly one YAML document")
        return ""
    return documents[0]


def nested_mapping(
    text: str,
    path: tuple[str, ...],
) -> tuple[str, int] | None:
    body = text
    child_indent = 0
    for key in path:
        result = yaml_section(body, key, indent=child_indent)
        if not result:
            return None
        body, parent_indent = result
        next_indent = direct_child_indent(body, parent_indent)
        if next_indent is None:
            return None
        child_indent = next_indent
    return body, child_indent


def mapping_scalars(
    text: str,
    *,
    indent: int,
    fields: tuple[str, ...],
    label: str,
    errors: list[str],
) -> dict[str, str] | None:
    values: dict[str, str] = {}
    valid = True
    for field in fields:
        value = yaml_scalar(text, field, indent=indent)
        if not value:
            errors.append(f"{label} has no unambiguous {field}")
            valid = False
        else:
            values[field] = value
    return values if valid else None


def yaml_sequence_items(text: str) -> list[tuple[str, int]]:
    lines = text.splitlines()
    entries = [
        (index, entry)
        for index, line in enumerate(lines)
        if (entry := yaml_mapping_entry(line)) is not None and entry[1]
    ]
    if not entries:
        return []
    item_indent = min(entry[0] for _, entry in entries)
    starts = [
        index
        for index, entry in entries
        if entry[0] == item_indent
    ]
    return [
        (
            "\n".join(
                lines[start : starts[position + 1]]
                if position + 1 < len(starts)
                else lines[start:]
            ),
            item_indent,
        )
        for position, start in enumerate(starts)
    ]


def decode_yaml_scalar(value: str) -> str | None:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        if value[0] == '"':
            try:
                decoded = json.loads(value)
            except json.JSONDecodeError:
                return None
            return decoded if isinstance(decoded, str) else None
        return value[1:-1].replace("''", "'")
    return value


def sequence_item_scalar(text: str, *, indent: int, key: str) -> str | None:
    values: list[str] = []
    for line in text.splitlines():
        entry = yaml_mapping_entry(line)
        if not entry:
            continue
        logical_indent, _, candidate, value = entry
        if logical_indent != indent or candidate != key or not value:
            continue
        decoded = decode_yaml_scalar(value)
        if decoded is not None:
            values.append(decoded)
    return values[0] if len(values) == 1 else None


def parse_contract_workload(
    contract: str,
    errors: list[str],
) -> WorkloadIdentity | None:
    workload = nested_mapping(contract, ("application", "workload"))
    if not workload:
        errors.append(
            "otel-connection.yaml has no structurally valid application.workload"
        )
        return None
    body, indent = workload
    values = mapping_scalars(
        body,
        indent=indent,
        fields=("apiVersion", "kind", "name", "namespace", "container"),
        label="otel-connection.yaml application.workload",
        errors=errors,
    )
    if not values:
        return None
    return WorkloadIdentity(
        api_version=values["apiVersion"],
        kind=values["kind"],
        name=values["name"],
        namespace=values["namespace"],
        container=values["container"],
    )


def parse_patch_workload(
    overlay: str,
    errors: list[str],
) -> WorkloadIdentity | None:
    root = mapping_scalars(
        overlay,
        indent=0,
        fields=("apiVersion", "kind"),
        label="application patch",
        errors=errors,
    )
    metadata = nested_mapping(overlay, ("metadata",))
    metadata_values = None
    if not metadata:
        errors.append("application patch has no structurally valid metadata")
    else:
        body, indent = metadata
        metadata_values = mapping_scalars(
            body,
            indent=indent,
            fields=("name", "namespace"),
            label="application patch metadata",
            errors=errors,
        )

    pod_spec = nested_mapping(overlay, ("spec", "template", "spec"))
    container: str | None = None
    if not pod_spec:
        errors.append("application patch has no structurally valid pod spec")
    else:
        body, indent = pod_spec
        containers = yaml_section(body, "containers", indent=indent)
        if not containers:
            errors.append("application patch has no target containers")
        else:
            container_body, _ = containers
            items = yaml_sequence_items(container_body)
            if len(items) != 1:
                errors.append(
                    "application patch must contain exactly one target container; "
                    f"found {len(items)}"
                )
            else:
                item, item_indent = items[0]
                container = sequence_item_scalar(
                    item,
                    indent=item_indent,
                    key="name",
                )
                if not container:
                    errors.append(
                        "application patch target container has no unambiguous name"
                    )

    if not root or not metadata_values or not container:
        return None
    return WorkloadIdentity(
        api_version=root["apiVersion"],
        kind=root["kind"],
        name=metadata_values["name"],
        namespace=metadata_values["namespace"],
        container=container,
    )


def parse_scaffold_workload(
    workload: str,
    errors: list[str],
) -> WorkloadIdentity | None:
    root = mapping_scalars(
        workload,
        indent=0,
        fields=("apiVersion", "kind"),
        label="scaffold workload",
        errors=errors,
    )
    metadata = nested_mapping(workload, ("metadata",))
    metadata_values = None
    if not metadata:
        errors.append("scaffold workload has no structurally valid metadata")
    else:
        body, indent = metadata
        metadata_values = mapping_scalars(
            body,
            indent=indent,
            fields=("name", "namespace"),
            label="scaffold workload metadata",
            errors=errors,
        )

    pod_spec = nested_mapping(workload, ("spec", "template", "spec"))
    container: str | None = None
    if not pod_spec:
        errors.append("scaffold workload has no structurally valid pod spec")
    else:
        body, indent = pod_spec
        containers = yaml_section(body, "containers", indent=indent)
        if not containers:
            errors.append("scaffold workload has no target containers")
        else:
            container_body, _ = containers
            items = yaml_sequence_items(container_body)
            if len(items) != 1:
                errors.append(
                    "scaffold workload must contain exactly one container; "
                    f"found {len(items)}"
                )
            else:
                item, item_indent = items[0]
                container = sequence_item_scalar(
                    item,
                    indent=item_indent,
                    key="name",
                )
                if not container:
                    errors.append(
                        "scaffold workload container has no unambiguous name"
                    )
                if not sequence_item_scalar(item, indent=item_indent, key="image"):
                    errors.append("scaffold workload container has no image")

    if not root or not metadata_values or not container:
        return None
    return WorkloadIdentity(
        api_version=root["apiVersion"],
        kind=root["kind"],
        name=metadata_values["name"],
        namespace=metadata_values["namespace"],
        container=container,
    )


def compare_workload_identities(
    contract: WorkloadIdentity,
    patch: WorkloadIdentity,
    errors: list[str],
) -> None:
    for attribute, label in (
        ("api_version", "apiVersion"),
        ("kind", "kind"),
        ("name", "workload name"),
        ("namespace", "namespace"),
        ("container", "target container"),
    ):
        if getattr(contract, attribute) != getattr(patch, attribute):
            errors.append(
                f"application patch {label} differs from otel-connection.yaml"
            )


def validate_workload_identity(
    label: str,
    identity: WorkloadIdentity,
    errors: list[str],
) -> None:
    if not DNS_SUBDOMAIN.fullmatch(identity.name):
        errors.append(f"{label} has an invalid workload name")
    if not DNS_LABEL.fullmatch(identity.namespace):
        errors.append(f"{label} has an invalid namespace")
    if not DNS_LABEL.fullmatch(identity.container):
        errors.append(f"{label} has an invalid container name")


def kustomize_target_name(value: str) -> str:
    return f"^{re.escape(value)}$"


def validate_kustomization_target(
    kustomization: str,
    contract: WorkloadIdentity | None,
    errors: list[str],
) -> None:
    if yaml_scalar(kustomization, "kind", indent=0) not in {
        "Kustomization",
        "Component",
    }:
        errors.append("kustomization.yaml is not a Kustomization or Component")

    patches = yaml_section(kustomization, "patches", indent=0)
    if not patches:
        errors.append("kustomization.yaml has no structurally valid patches list")
        return
    patch_body, _ = patches
    items = yaml_sequence_items(patch_body)
    if len(items) != 1:
        errors.append(
            "kustomization.yaml must contain exactly one generated patch entry; "
            f"found {len(items)}"
        )
        return
    item, item_indent = items[0]
    patch_path = sequence_item_scalar(item, indent=item_indent, key="path")
    if patch_path != "otel-env-patch.yaml":
        errors.append(
            "kustomization.yaml does not structurally reference the generated patch"
        )

    target = yaml_section(item, "target", indent=item_indent)
    if not target:
        errors.append("kustomization.yaml generated patch has no target")
        return
    target_body, target_indent = target
    child_indent = direct_child_indent(target_body, target_indent)
    if child_indent is None:
        errors.append("kustomization.yaml generated patch target is empty")
        return
    values = mapping_scalars(
        target_body,
        indent=child_indent,
        fields=("group", "version", "kind", "name", "namespace"),
        label="kustomization.yaml generated patch target",
        errors=errors,
    )
    if not values or not contract:
        return
    try:
        expected_group, expected_version = contract.api_version.split("/", 1)
    except ValueError:
        errors.append(
            "otel-connection.yaml application workload has invalid apiVersion"
        )
        return
    expected = {
        "group": expected_group,
        "version": expected_version,
        "kind": contract.kind,
        "name": kustomize_target_name(contract.name),
        "namespace": contract.namespace,
    }
    for field, value in expected.items():
        if values[field] != value:
            label = "apiVersion" if field in {"group", "version"} else field
            errors.append(
                f"kustomization.yaml generated patch target {label} differs "
                "from otel-connection.yaml"
            )


def quoted_value(text: str, key: str) -> str | None:
    match = re.search(
        rf"^\s*{re.escape(key)}:\s*\"([^\"\r\n]*)\"\s*$",
        text,
        re.MULTILINE,
    )
    return match.group(1) if match else None


def integer_value(text: str, key: str) -> int | None:
    match = re.search(
        rf"^\s*{re.escape(key)}:\s*([0-9]+)\s*$", text, re.MULTILINE
    )
    return int(match.group(1)) if match else None


def section(text: str, key: str) -> str:
    lines = text.splitlines()
    for index, line in enumerate(lines):
        match = re.fullmatch(rf"(?P<indent>\s*){re.escape(key)}:\s*", line)
        if not match:
            continue
        parent_indent = len(match.group("indent"))
        body: list[str] = []
        for child in lines[index + 1 :]:
            if not child.strip():
                body.append(child)
                continue
            child_indent = len(child) - len(child.lstrip())
            if child_indent <= parent_indent:
                break
            body.append(child)
        return "\n".join(body) + ("\n" if body else "")
    return ""


def validate_endpoint(
    endpoint: str,
    *,
    service: str | None,
    namespace: str | None,
    expected_port: int,
) -> bool:
    try:
        parsed = urlsplit(endpoint)
        port = parsed.port
    except ValueError:
        return False
    if (
        parsed.scheme != "http"
        or parsed.username is not None
        or parsed.password is not None
        or parsed.path
        or parsed.query
        or parsed.fragment
        or port != expected_port
        or parsed.hostname is None
    ):
        return False
    labels = parsed.hostname.split(".")
    if len(labels) < 3 or labels[2] != "svc":
        return False
    if not all(DNS_LABEL.fullmatch(label) for label in labels):
        return False
    return labels[0] == service and labels[1] == namespace


def read_managed(path: Path, errors: list[str]) -> str:
    if path.is_symlink():
        errors.append(f"managed file must not be a symlink: {path}")
        return ""
    if not path.is_file():
        errors.append(f"missing required file: {path}")
        return ""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        errors.append(f"cannot read {path}: {exc}")
        return ""
    if not text.startswith(tuple(f"{marker}\n" for marker in OWNER_MARKERS)):
        errors.append(f"missing ownership marker: {path}")
    return text


def validate(bundle: Path) -> list[str]:
    errors: list[str] = []
    if bundle.is_symlink():
        return [f"configuration directory must not be a symlink: {bundle}"]
    if not bundle.is_dir():
        return [f"configuration directory does not exist: {bundle}"]

    contents = {
        relative: read_managed(bundle / relative, errors)
        for relative in REQUIRED_FILES
    }
    initial_contract = contents[Path("otel-connection.yaml")]
    initial_application = section(initial_contract, "application")
    overlay_mode = quoted_value(initial_application, "overlayMode")
    if overlay_mode not in {"component", "scaffold", "standalone"}:
        errors.append("otel-connection.yaml has an invalid application overlayMode")
    scaffold_mode = overlay_mode == "scaffold"
    if scaffold_mode:
        contents[SCAFFOLD_WORKLOAD_FILE] = read_managed(
            bundle / SCAFFOLD_WORKLOAD_FILE,
            errors,
        )
    elif (bundle / SCAFFOLD_WORKLOAD_FILE).exists():
        errors.append(
            "kubernetes/workload.yaml exists but application overlayMode "
            "is not scaffold"
        )
    hashes: set[str] = set()
    for relative, text in contents.items():
        match = HASH.search(text)
        if not match:
            errors.append(f"{relative} has no valid input hash")
        else:
            hashes.add(match.group(1))
    if len(hashes) > 1:
        errors.append("managed files were generated from different inputs")

    contract = contents[REQUIRED_FILES[0]]
    kustomization = contents[REQUIRED_FILES[1]]
    overlay = contents[REQUIRED_FILES[2]]
    scaffold_workload = contents.get(SCAFFOLD_WORKLOAD_FILE, "")
    for relative, text in contents.items():
        if text:
            errors.extend(
                duplicate_yaml_mapping_keys(relative.as_posix(), text)
            )

    contract_document = (
        single_yaml_document(
            contract,
            label="otel-connection.yaml",
            errors=errors,
        )
        if contract
        else ""
    )
    kustomization_document = (
        single_yaml_document(
            kustomization,
            label="kustomization.yaml",
            errors=errors,
        )
        if kustomization
        else ""
    )
    overlay_document = (
        single_yaml_document(
            overlay,
            label="otel-env-patch.yaml",
            errors=errors,
        )
        if overlay
        else ""
    )
    scaffold_document = (
        single_yaml_document(
            scaffold_workload,
            label="workload.yaml",
            errors=errors,
        )
        if scaffold_workload
        else ""
    )
    contract_workload = (
        parse_contract_workload(contract_document, errors)
        if contract_document
        else None
    )
    patch_workload = (
        parse_patch_workload(overlay_document, errors)
        if overlay_document
        else None
    )
    if contract_workload and patch_workload:
        validate_workload_identity(
            "otel-connection.yaml application workload",
            contract_workload,
            errors,
        )
        validate_workload_identity(
            "application patch",
            patch_workload,
            errors,
        )
        compare_workload_identities(contract_workload, patch_workload, errors)
    scaffold_identity = (
        parse_scaffold_workload(scaffold_document, errors)
        if scaffold_document
        else None
    )
    if contract_workload and scaffold_identity:
        validate_workload_identity(
            "scaffold workload",
            scaffold_identity,
            errors,
        )
        compare_workload_identities(contract_workload, scaffold_identity, errors)
    if kustomization_document:
        kustomization_kind = yaml_scalar(kustomization_document, "kind", indent=0)
        if overlay_mode == "component" and kustomization_kind != "Component":
            errors.append("component overlayMode requires a Component kustomization")
        if overlay_mode in {"scaffold", "standalone"} and kustomization_kind != "Kustomization":
            errors.append(
                f"{overlay_mode} overlayMode requires a Kustomization"
            )
        has_resources = yaml_section(kustomization_document, "resources", indent=0)
        if overlay_mode == "standalone" and not has_resources:
            errors.append("standalone overlayMode requires kustomization resources")
        if overlay_mode == "component" and has_resources:
            errors.append("component overlayMode must not define kustomization resources")
        validate_kustomization_target(
            kustomization_document,
            contract_workload,
            errors,
        )
        if scaffold_mode and 'workload.yaml' not in kustomization_document:
            errors.append("scaffold kustomization does not reference workload.yaml")

    for required in (
        "schemaVersion: 1",
        'kind: "otel-connection"',
        'platform: "kubernetes"',
        'usage: "collector-egress-only"',
        'liveRoute: "unverified"',
        'mode: "plaintext-cluster-local"',
    ):
        if required not in contract:
            errors.append(f"otel-connection.yaml missing required value: {required}")

    protocol = quoted_value(contract, "protocol")
    endpoint = quoted_value(contract, "endpoint")
    traces_endpoint = quoted_value(contract, "tracesEndpoint")
    metrics_endpoint = quoted_value(contract, "metricsEndpoint")
    contract_port = integer_value(section(contract, "otlp"), "port")
    port_name = quoted_value(section(contract, "otlp"), "portName")
    collector = section(contract, "collector")
    collector_service = quoted_value(collector, "service")
    collector_namespace = quoted_value(collector, "namespace")
    secret = section(collector, "secretRef")
    secret_name = quoted_value(secret, "name")
    secret_namespace = quoted_value(secret, "namespace")
    realm = quoted_value(section(contract, "splunkObservability"), "realm")
    if protocol not in {"http/protobuf", "grpc"}:
        errors.append("otel-connection.yaml has an invalid OTLP protocol")
    if endpoint is None:
        errors.append("otel-connection.yaml has no OTLP endpoint")
    else:
        port = 4318 if protocol == "http/protobuf" else 4317
        expected_port_name = "otlp-http" if protocol == "http/protobuf" else "otlp"
        if not validate_endpoint(
            endpoint,
            service=collector_service,
            namespace=collector_namespace,
            expected_port=port,
        ):
            errors.append("OTLP endpoint is not a valid in-cluster Service route")
        if contract_port != port:
            errors.append("OTLP port does not match the selected protocol")
        if port_name != expected_port_name:
            errors.append("OTLP port name does not match the selected protocol")
        expected_traces = (
            f"{endpoint}/v1/traces" if protocol == "http/protobuf" else endpoint
        )
        expected_metrics = (
            f"{endpoint}/v1/metrics" if protocol == "http/protobuf" else endpoint
        )
        if traces_endpoint != expected_traces:
            errors.append("trace endpoint does not match protocol and base endpoint")
        if metrics_endpoint != expected_metrics:
            errors.append("metric endpoint does not match protocol and base endpoint")

    if not secret_name:
        errors.append("collector Secret reference has no name")
    elif not DNS_SUBDOMAIN.fullmatch(secret_name):
        errors.append("collector Secret reference has an invalid name")
    if secret_namespace and not DNS_LABEL.fullmatch(secret_namespace):
        errors.append("collector Secret reference has an invalid namespace")
    if secret_namespace != collector_namespace:
        errors.append("collector Secret reference must use the collector namespace")
    if not realm:
        errors.append("Splunk Observability realm is missing")
    if re.search(r"^\s*(?:accessToken|stringData|X-SF-Token)\s*:", contract, re.I | re.M):
        errors.append("connection contract contains inline token material")

    for forbidden in FORBIDDEN_OVERLAY:
        if forbidden.lower() in overlay.lower():
            errors.append(f"application overlay contains forbidden value: {forbidden}")
        if scaffold_workload and forbidden.lower() in scaffold_workload.lower():
            errors.append(f"scaffold workload contains forbidden value: {forbidden}")
    expected_env = {
        "OTEL_SERVICE_NAME": quoted_value(contract, "serviceName"),
        "OTEL_EXPORTER_OTLP_ENDPOINT": endpoint,
        "OTEL_EXPORTER_OTLP_PROTOCOL": protocol,
        "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT": traces_endpoint,
        "OTEL_EXPORTER_OTLP_TRACES_PROTOCOL": protocol,
        "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT": metrics_endpoint,
        "OTEL_EXPORTER_OTLP_METRICS_PROTOCOL": protocol,
    }
    env_entries = re.findall(
        r'^\s*name:\s*"(OTEL_[A-Z0-9_]+)"\s*$\n'
        r'^\s*value:\s*"([^"\r\n]*)"\s*$',
        overlay,
        re.MULTILINE,
    )
    actual_env: dict[str, str] = {}
    for name, value in env_entries:
        if name in actual_env:
            errors.append(f"application overlay contains duplicate env var: {name}")
        actual_env[name] = value
    for label, forbidden in (("collector Secret name", secret_name), ("realm", realm)):
        if forbidden and forbidden in actual_env.values():
            errors.append(f"application overlay contains forbidden {label}")
    for name, value in expected_env.items():
        if value is None or actual_env.get(name) != value:
            errors.append(f"application overlay has inconsistent {name}")

    contract_hash = next(iter(hashes), None)
    if contract_hash and contract_hash not in overlay:
        errors.append("application overlay annotation does not match input hash")
    if scaffold_workload and contract_hash and contract_hash not in scaffold_workload:
        errors.append("scaffold workload annotation does not match input hash")
    return errors


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("config_dir", type=Path)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    errors = validate(args.config_dir)
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print(f"Validated static OTel application configuration: {args.config_dir}")
    print("Live Collector Service readiness remains unverified.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
