// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.19.1
// source: opentelemetry/proto/profiles/v1development/profiles.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AnyValue, InstrumentationScope } from "../../common/v1/common";
import { Resource } from "../../resource/v1/resource";

/**
 * ProfilesDictionary represents the profiles data shared across the
 * entire message being sent. The following applies to all fields in this
 * message:
 *
 * - A dictionary is an array of dictionary items. Users of the dictionary
 *   compactly reference the items using the index within the array.
 *
 * - A dictionary MUST have a zero value encoded as the first element. This
 *   allows for _index fields pointing into the dictionary to use a 0 pointer
 *   value to indicate 'null' / 'not set'. Unless otherwise defined, a 'zero
 *   value' message value is one with all default field values, so as to
 *   minimize wire encoded size.
 *
 * - There SHOULD NOT be dupes in a dictionary. The identity of dictionary
 *   items is based on their value, recursively as needed. If a particular
 *   implementation does emit duplicated items, it MUST NOT attempt to give them
 *   meaning based on the index or order. A profile processor may remove
 *   duplicate items and this MUST NOT have any observable effects for
 *   consumers.
 *
 * - There SHOULD NOT be orphaned (unreferenced) items in a dictionary. A
 *   profile processor may remove ("garbage-collect") orphaned items and this
 *   MUST NOT have any observable effects for consumers.
 */
export interface ProfilesDictionary {
  /**
   * Mappings from address ranges to the image/binary/library mapped
   * into that address range referenced by locations via Location.mapping_index.
   *
   * mapping_table[0] must always be zero value (Mapping{}) and present.
   */
  mappingTable: Mapping[];
  /**
   * Locations referenced by samples via Stack.location_indices.
   *
   * location_table[0] must always be zero value (Location{}) and present.
   */
  locationTable: Location[];
  /**
   * Functions referenced by locations via Line.function_index.
   *
   * function_table[0] must always be zero value (Function{}) and present.
   */
  functionTable: FunctionMessage[];
  /**
   * Links referenced by samples via Sample.link_index.
   *
   * link_table[0] must always be zero value (Link{}) and present.
   */
  linkTable: Link[];
  /**
   * A common table for strings referenced by various messages.
   *
   * string_table[0] must always be "" and present.
   */
  stringTable: string[];
  /**
   * A common table for attributes referenced by the Profile, Sample, Mapping
   * and Location messages below through attribute_indices field. Each entry is
   * a key/value pair with an optional unit. Since this is a dictionary table,
   * multiple entries with the same key may be present, unlike direct attribute
   * tables like Resource.attributes. The referencing attribute_indices fields,
   * though, do maintain the key uniqueness requirement.
   *
   * It's recommended to use attributes for variables with bounded cardinality,
   * such as categorical variables
   * (https://en.wikipedia.org/wiki/Categorical_variable). Using an attribute of
   * a floating point type (e.g., CPU time) in a sample can quickly make every
   * attribute value unique, defeating the purpose of the dictionary and
   * impractically increasing the profile size.
   *
   * Examples of attributes:
   *     "/http/user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
   *     "abc.com/myattribute": true
   *     "allocation_size": 128 bytes
   *
   * attribute_table[0] must always be zero value (KeyValueAndUnit{}) and present.
   */
  attributeTable: KeyValueAndUnit[];
  /**
   * Stacks referenced by samples via Sample.stack_index.
   *
   * stack_table[0] must always be zero value (Stack{}) and present.
   */
  stackTable: Stack[];
}

/**
 * ProfilesData represents the profiles data that can be stored in persistent storage,
 * OR can be embedded by other protocols that transfer OTLP profiles data but do not
 * implement the OTLP protocol.
 *
 * The main difference between this message and collector protocol is that
 * in this message there will not be any "control" or "metadata" specific to
 * OTLP protocol.
 *
 * When new fields are added into this message, the OTLP request MUST be updated
 * as well.
 */
export interface ProfilesData {
  /**
   * An array of ResourceProfiles.
   * For data coming from an SDK profiler, this array will typically contain one
   * element. Host-level profilers will usually create one ResourceProfile per
   * container, as well as one additional ResourceProfile grouping all samples
   * from non-containerized processes.
   * Other resource groupings are possible as well and clarified via
   * Resource.attributes and semantic conventions.
   * Tools that visualize profiles should prefer displaying
   * resources_profiles[0].scope_profiles[0].profiles[0] by default.
   */
  resourceProfiles: ResourceProfiles[];
  /** One instance of ProfilesDictionary */
  dictionary?: ProfilesDictionary | undefined;
}

/** A collection of ScopeProfiles from a Resource. */
export interface ResourceProfiles {
  /**
   * The resource for the profiles in this message.
   * If this field is not set then no resource info is known.
   */
  resource?:
    | Resource
    | undefined;
  /** A list of ScopeProfiles that originate from a resource. */
  scopeProfiles: ScopeProfiles[];
  /**
   * The Schema URL, if known. This is the identifier of the Schema that the resource data
   * is recorded in. Notably, the last part of the URL path is the version number of the
   * schema: http[s]://server[:port]/path/<version>. To learn more about Schema URL see
   * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
   * This schema_url applies to the data in the "resource" field. It does not apply
   * to the data in the "scope_profiles" field which have their own schema_url field.
   */
  schemaUrl: string;
}

/** A collection of Profiles produced by an InstrumentationScope. */
export interface ScopeProfiles {
  /**
   * The instrumentation scope information for the profiles in this message.
   * Semantically when InstrumentationScope isn't set, it is equivalent with
   * an empty instrumentation scope name (unknown).
   */
  scope?:
    | InstrumentationScope
    | undefined;
  /** A list of Profiles that originate from an instrumentation scope. */
  profiles: Profile[];
  /**
   * The Schema URL, if known. This is the identifier of the Schema that the profile data
   * is recorded in. Notably, the last part of the URL path is the version number of the
   * schema: http[s]://server[:port]/path/<version>. To learn more about Schema URL see
   * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
   * This schema_url applies to the data in the "scope" field and all profiles in the
   * "profiles" field.
   */
  schemaUrl: string;
}

/**
 * Represents a complete profile, including sample types, samples, mappings to
 * binaries, stacks, locations, functions, string table, and additional
 * metadata. It modifies and annotates pprof Profile with OpenTelemetry
 * specific fields.
 *
 * Note that whilst fields in this message retain the name and field id from pprof in most cases
 * for ease of understanding data migration, it is not intended that pprof:Profile and
 * OpenTelemetry:Profile encoding be wire compatible.
 */
export interface Profile {
  /**
   * The type and unit of all Sample.values in this profile.
   * For a cpu or off-cpu profile this might be:
   *   ["cpu","nanoseconds"] or ["off_cpu","nanoseconds"]
   * For a heap profile, this might be:
   *   ["allocated_objects","count"] or ["allocated_space","bytes"],
   */
  sampleType?:
    | ValueType
    | undefined;
  /** The set of samples recorded in this profile. */
  samples: Sample[];
  /** Time of collection (UTC) represented as nanoseconds past the epoch. */
  timeUnixNano: string;
  /** Duration of the profile, if a duration makes sense. */
  durationNano: string;
  /**
   * The kind of events between sampled occurrences.
   * e.g [ "cpu","cycles" ] or [ "heap","bytes" ]
   */
  periodType?:
    | ValueType
    | undefined;
  /** The number of events between sampled occurrences. */
  period: string;
  /**
   * A globally unique identifier for a profile. The ID is a 16-byte array. An ID with
   * all zeroes is considered invalid. It may be used for deduplication and signal
   * correlation purposes. It is acceptable to treat two profiles with different values
   * in this field as not equal, even if they represented the same object at an earlier
   * time.
   * This field is optional; an ID may be assigned to an ID-less profile in a later step.
   */
  profileId: Uint8Array;
  /**
   * The number of attributes that were discarded. Attributes
   * can be discarded because their keys are too long or because there are too many
   * attributes. If this value is 0, then no attributes were dropped.
   */
  droppedAttributesCount: number;
  /**
   * The original payload format. See also original_payload. Optional, but the
   * format and the bytes must be set or unset together.
   *
   * The allowed values for the format string are defined by the OpenTelemetry
   * specification. Some examples are "jfr", "pprof", "linux_perf".
   *
   * The original payload may be optionally provided when the conversion to the
   * OLTP format was done from a different format with some loss of the fidelity
   * and the receiver may want to store the original payload to allow future
   * lossless export or reinterpretation. Some examples of the original format
   * are JFR (Java Flight Recorder), pprof, Linux perf.
   *
   * Even when the original payload is in a format that is semantically close to
   * OTLP, such as pprof, a conversion may still be lossy in some cases (e.g. if
   * the pprof file contains custom extensions or conventions).
   *
   * The original payload can be large in size, so including the original
   * payload should be configurable by the profiler or collector options. The
   * default behavior should be to not include the original payload.
   */
  originalPayloadFormat: string;
  /**
   * The original payload bytes. See also original_payload_format. Optional, but
   * format and the bytes must be set or unset together.
   */
  originalPayload: Uint8Array;
  /** References to attributes in attribute_table. [optional] */
  attributeIndices: number[];
}

/**
 * A pointer from a profile Sample to a trace Span.
 * Connects a profile sample to a trace span, identified by unique trace and span IDs.
 */
export interface Link {
  /**
   * A unique identifier of a trace that this linked span is part of. The ID is a
   * 16-byte array.
   */
  traceId: Uint8Array;
  /** A unique identifier for the linked span. The ID is an 8-byte array. */
  spanId: Uint8Array;
}

/** ValueType describes the type and units of a value. */
export interface ValueType {
  /** Index into ProfilesDictionary.string_table. */
  typeStrindex: number;
  /** Index into ProfilesDictionary.string_table. */
  unitStrindex: number;
}

/**
 * Each Sample records values encountered in some program context. The program
 * context is typically a stack trace, perhaps augmented with auxiliary
 * information like the thread-id, some indicator of a higher level request
 * being handled etc.
 *
 * A Sample MUST have have at least one values or timestamps_unix_nano entry. If
 * both fields are populated, they MUST contain the same number of elements, and
 * the elements at the same index MUST refer to the same event.
 *
 * Examples of different ways of representing a sample with the total value of 10:
 *
 * Report of a stacktrace at 10 timestamps (consumers must assume the value is 1 for each point):
 *    values: []
 *    timestamps_unix_nano: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
 *
 * Report of a stacktrace with an aggregated value without timestamps:
 *   values: [10]
 *    timestamps_unix_nano: []
 *
 * Report of a stacktrace at 4 timestamps where each point records a specific value:
 *    values: [2, 2, 3, 3]
 *    timestamps_unix_nano: [1, 2, 3, 4]
 */
export interface Sample {
  /** Reference to stack in ProfilesDictionary.stack_table. */
  stackIndex: number;
  /** The type and unit of each value is defined by Profile.sample_type. */
  values: string[];
  /** References to attributes in ProfilesDictionary.attribute_table. [optional] */
  attributeIndices: number[];
  /**
   * Reference to link in ProfilesDictionary.link_table. [optional]
   * It can be unset / set to 0 if no link exists, as link_table[0] is always a 'null' default value.
   */
  linkIndex: number;
  /**
   * Timestamps associated with Sample represented in nanoseconds. These
   * timestamps should fall within the Profile's time range.
   */
  timestampsUnixNano: string[];
}

/**
 * Describes the mapping of a binary in memory, including its address range,
 * file offset, and metadata like build ID
 */
export interface Mapping {
  /** Address at which the binary (or DLL) is loaded into memory. */
  memoryStart: string;
  /** The limit of the address range occupied by this mapping. */
  memoryLimit: string;
  /** Offset in the binary that corresponds to the first mapped address. */
  fileOffset: string;
  /**
   * The object this entry is loaded from.  This can be a filename on
   * disk for the main binary and shared libraries, or virtual
   * abstractions like "[vdso]".
   */
  filenameStrindex: number;
  /** References to attributes in ProfilesDictionary.attribute_table. [optional] */
  attributeIndices: number[];
}

/** A Stack represents a stack trace as a list of locations. */
export interface Stack {
  /**
   * References to locations in ProfilesDictionary.location_table.
   * The first location is the leaf frame.
   */
  locationIndices: number[];
}

/** Describes function and line table debug information. */
export interface Location {
  /**
   * Reference to mapping in ProfilesDictionary.mapping_table.
   * It can be unset / set to 0 if the mapping is unknown or not applicable for
   * this profile type, as mapping_table[0] is always a 'null' default mapping.
   */
  mappingIndex: number;
  /**
   * The instruction address for this location, if available.  It
   * should be within [Mapping.memory_start...Mapping.memory_limit]
   * for the corresponding mapping. A non-leaf address may be in the
   * middle of a call instruction. It is up to display tools to find
   * the beginning of the instruction if necessary.
   */
  address: string;
  /**
   * Multiple line indicates this location has inlined functions,
   * where the last entry represents the caller into which the
   * preceding entries were inlined.
   *
   * E.g., if memcpy() is inlined into printf:
   *    lines[0].function_name == "memcpy"
   *    lines[1].function_name == "printf"
   */
  lines: Line[];
  /** References to attributes in ProfilesDictionary.attribute_table. [optional] */
  attributeIndices: number[];
}

/** Details a specific line in a source code, linked to a function. */
export interface Line {
  /** Reference to function in ProfilesDictionary.function_table. */
  functionIndex: number;
  /** Line number in source code. 0 means unset. */
  line: string;
  /** Column number in source code. 0 means unset. */
  column: string;
}

/**
 * Describes a function, including its human-readable name, system name,
 * source file, and starting line number in the source.
 */
export interface FunctionMessage {
  /** The function name. Empty string if not available. */
  nameStrindex: number;
  /**
   * Function name, as identified by the system. For instance,
   * it can be a C++ mangled name. Empty string if not available.
   */
  systemNameStrindex: number;
  /** Source file containing the function. Empty string if not available. */
  filenameStrindex: number;
  /** Line number in source file. 0 means unset. */
  startLine: string;
}

/**
 * A custom 'dictionary native' style of encoding attributes which is more convenient
 * for profiles than opentelemetry.proto.common.v1.KeyValue
 * Specifically, uses the string table for keys and allows optional unit information.
 */
export interface KeyValueAndUnit {
  /** The index into the string table for the attribute's key. */
  keyStrindex: number;
  /** The value of the attribute. */
  value?:
    | AnyValue
    | undefined;
  /**
   * The index into the string table for the attribute's unit.
   * zero indicates implicit (by semconv) or non-defined unit.
   */
  unitStrindex: number;
}

function createBaseProfilesDictionary(): ProfilesDictionary {
  return {
    mappingTable: [],
    locationTable: [],
    functionTable: [],
    linkTable: [],
    stringTable: [],
    attributeTable: [],
    stackTable: [],
  };
}

export const ProfilesDictionary: MessageFns<ProfilesDictionary> = {
  encode(message: ProfilesDictionary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.mappingTable) {
      Mapping.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.locationTable) {
      Location.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.functionTable) {
      FunctionMessage.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.linkTable) {
      Link.encode(v!, writer.uint32(34).fork()).join();
    }
    for (const v of message.stringTable) {
      writer.uint32(42).string(v!);
    }
    for (const v of message.attributeTable) {
      KeyValueAndUnit.encode(v!, writer.uint32(50).fork()).join();
    }
    for (const v of message.stackTable) {
      Stack.encode(v!, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProfilesDictionary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProfilesDictionary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.mappingTable.push(Mapping.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.locationTable.push(Location.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.functionTable.push(FunctionMessage.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.linkTable.push(Link.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.stringTable.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.attributeTable.push(KeyValueAndUnit.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.stackTable.push(Stack.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProfilesDictionary {
    return {
      mappingTable: globalThis.Array.isArray(object?.mappingTable)
        ? object.mappingTable.map((e: any) => Mapping.fromJSON(e))
        : globalThis.Array.isArray(object?.mapping_table)
        ? object.mapping_table.map((e: any) => Mapping.fromJSON(e))
        : [],
      locationTable: globalThis.Array.isArray(object?.locationTable)
        ? object.locationTable.map((e: any) => Location.fromJSON(e))
        : globalThis.Array.isArray(object?.location_table)
        ? object.location_table.map((e: any) => Location.fromJSON(e))
        : [],
      functionTable: globalThis.Array.isArray(object?.functionTable)
        ? object.functionTable.map((e: any) => FunctionMessage.fromJSON(e))
        : globalThis.Array.isArray(object?.function_table)
        ? object.function_table.map((e: any) => FunctionMessage.fromJSON(e))
        : [],
      linkTable: globalThis.Array.isArray(object?.linkTable)
        ? object.linkTable.map((e: any) => Link.fromJSON(e))
        : globalThis.Array.isArray(object?.link_table)
        ? object.link_table.map((e: any) => Link.fromJSON(e))
        : [],
      stringTable: globalThis.Array.isArray(object?.stringTable)
        ? object.stringTable.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.string_table)
        ? object.string_table.map((e: any) => globalThis.String(e))
        : [],
      attributeTable: globalThis.Array.isArray(object?.attributeTable)
        ? object.attributeTable.map((e: any) => KeyValueAndUnit.fromJSON(e))
        : globalThis.Array.isArray(object?.attribute_table)
        ? object.attribute_table.map((e: any) => KeyValueAndUnit.fromJSON(e))
        : [],
      stackTable: globalThis.Array.isArray(object?.stackTable)
        ? object.stackTable.map((e: any) => Stack.fromJSON(e))
        : globalThis.Array.isArray(object?.stack_table)
        ? object.stack_table.map((e: any) => Stack.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ProfilesDictionary): unknown {
    const obj: any = {};
    if (message.mappingTable?.length) {
      obj.mappingTable = message.mappingTable.map((e) => Mapping.toJSON(e));
    }
    if (message.locationTable?.length) {
      obj.locationTable = message.locationTable.map((e) => Location.toJSON(e));
    }
    if (message.functionTable?.length) {
      obj.functionTable = message.functionTable.map((e) => FunctionMessage.toJSON(e));
    }
    if (message.linkTable?.length) {
      obj.linkTable = message.linkTable.map((e) => Link.toJSON(e));
    }
    if (message.stringTable?.length) {
      obj.stringTable = message.stringTable;
    }
    if (message.attributeTable?.length) {
      obj.attributeTable = message.attributeTable.map((e) => KeyValueAndUnit.toJSON(e));
    }
    if (message.stackTable?.length) {
      obj.stackTable = message.stackTable.map((e) => Stack.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProfilesDictionary>, I>>(base?: I): ProfilesDictionary {
    return ProfilesDictionary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProfilesDictionary>, I>>(object: I): ProfilesDictionary {
    const message = createBaseProfilesDictionary();
    message.mappingTable = object.mappingTable?.map((e) => Mapping.fromPartial(e)) || [];
    message.locationTable = object.locationTable?.map((e) => Location.fromPartial(e)) || [];
    message.functionTable = object.functionTable?.map((e) => FunctionMessage.fromPartial(e)) || [];
    message.linkTable = object.linkTable?.map((e) => Link.fromPartial(e)) || [];
    message.stringTable = object.stringTable?.map((e) => e) || [];
    message.attributeTable = object.attributeTable?.map((e) => KeyValueAndUnit.fromPartial(e)) || [];
    message.stackTable = object.stackTable?.map((e) => Stack.fromPartial(e)) || [];
    return message;
  },
};

function createBaseProfilesData(): ProfilesData {
  return { resourceProfiles: [], dictionary: undefined };
}

export const ProfilesData: MessageFns<ProfilesData> = {
  encode(message: ProfilesData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.resourceProfiles) {
      ResourceProfiles.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.dictionary !== undefined) {
      ProfilesDictionary.encode(message.dictionary, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProfilesData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProfilesData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.resourceProfiles.push(ResourceProfiles.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.dictionary = ProfilesDictionary.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProfilesData {
    return {
      resourceProfiles: globalThis.Array.isArray(object?.resourceProfiles)
        ? object.resourceProfiles.map((e: any) => ResourceProfiles.fromJSON(e))
        : globalThis.Array.isArray(object?.resource_profiles)
        ? object.resource_profiles.map((e: any) => ResourceProfiles.fromJSON(e))
        : [],
      dictionary: isSet(object.dictionary) ? ProfilesDictionary.fromJSON(object.dictionary) : undefined,
    };
  },

  toJSON(message: ProfilesData): unknown {
    const obj: any = {};
    if (message.resourceProfiles?.length) {
      obj.resourceProfiles = message.resourceProfiles.map((e) => ResourceProfiles.toJSON(e));
    }
    if (message.dictionary !== undefined) {
      obj.dictionary = ProfilesDictionary.toJSON(message.dictionary);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProfilesData>, I>>(base?: I): ProfilesData {
    return ProfilesData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProfilesData>, I>>(object: I): ProfilesData {
    const message = createBaseProfilesData();
    message.resourceProfiles = object.resourceProfiles?.map((e) => ResourceProfiles.fromPartial(e)) || [];
    message.dictionary = (object.dictionary !== undefined && object.dictionary !== null)
      ? ProfilesDictionary.fromPartial(object.dictionary)
      : undefined;
    return message;
  },
};

function createBaseResourceProfiles(): ResourceProfiles {
  return { resource: undefined, scopeProfiles: [], schemaUrl: "" };
}

export const ResourceProfiles: MessageFns<ResourceProfiles> = {
  encode(message: ResourceProfiles, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.resource !== undefined) {
      Resource.encode(message.resource, writer.uint32(10).fork()).join();
    }
    for (const v of message.scopeProfiles) {
      ScopeProfiles.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.schemaUrl !== "") {
      writer.uint32(26).string(message.schemaUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResourceProfiles {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResourceProfiles();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.resource = Resource.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.scopeProfiles.push(ScopeProfiles.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.schemaUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResourceProfiles {
    return {
      resource: isSet(object.resource) ? Resource.fromJSON(object.resource) : undefined,
      scopeProfiles: globalThis.Array.isArray(object?.scopeProfiles)
        ? object.scopeProfiles.map((e: any) => ScopeProfiles.fromJSON(e))
        : globalThis.Array.isArray(object?.scope_profiles)
        ? object.scope_profiles.map((e: any) => ScopeProfiles.fromJSON(e))
        : [],
      schemaUrl: isSet(object.schemaUrl)
        ? globalThis.String(object.schemaUrl)
        : isSet(object.schema_url)
        ? globalThis.String(object.schema_url)
        : "",
    };
  },

  toJSON(message: ResourceProfiles): unknown {
    const obj: any = {};
    if (message.resource !== undefined) {
      obj.resource = Resource.toJSON(message.resource);
    }
    if (message.scopeProfiles?.length) {
      obj.scopeProfiles = message.scopeProfiles.map((e) => ScopeProfiles.toJSON(e));
    }
    if (message.schemaUrl !== "") {
      obj.schemaUrl = message.schemaUrl;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ResourceProfiles>, I>>(base?: I): ResourceProfiles {
    return ResourceProfiles.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ResourceProfiles>, I>>(object: I): ResourceProfiles {
    const message = createBaseResourceProfiles();
    message.resource = (object.resource !== undefined && object.resource !== null)
      ? Resource.fromPartial(object.resource)
      : undefined;
    message.scopeProfiles = object.scopeProfiles?.map((e) => ScopeProfiles.fromPartial(e)) || [];
    message.schemaUrl = object.schemaUrl ?? "";
    return message;
  },
};

function createBaseScopeProfiles(): ScopeProfiles {
  return { scope: undefined, profiles: [], schemaUrl: "" };
}

export const ScopeProfiles: MessageFns<ScopeProfiles> = {
  encode(message: ScopeProfiles, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.scope !== undefined) {
      InstrumentationScope.encode(message.scope, writer.uint32(10).fork()).join();
    }
    for (const v of message.profiles) {
      Profile.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.schemaUrl !== "") {
      writer.uint32(26).string(message.schemaUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScopeProfiles {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScopeProfiles();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.scope = InstrumentationScope.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.profiles.push(Profile.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.schemaUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScopeProfiles {
    return {
      scope: isSet(object.scope) ? InstrumentationScope.fromJSON(object.scope) : undefined,
      profiles: globalThis.Array.isArray(object?.profiles) ? object.profiles.map((e: any) => Profile.fromJSON(e)) : [],
      schemaUrl: isSet(object.schemaUrl)
        ? globalThis.String(object.schemaUrl)
        : isSet(object.schema_url)
        ? globalThis.String(object.schema_url)
        : "",
    };
  },

  toJSON(message: ScopeProfiles): unknown {
    const obj: any = {};
    if (message.scope !== undefined) {
      obj.scope = InstrumentationScope.toJSON(message.scope);
    }
    if (message.profiles?.length) {
      obj.profiles = message.profiles.map((e) => Profile.toJSON(e));
    }
    if (message.schemaUrl !== "") {
      obj.schemaUrl = message.schemaUrl;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScopeProfiles>, I>>(base?: I): ScopeProfiles {
    return ScopeProfiles.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScopeProfiles>, I>>(object: I): ScopeProfiles {
    const message = createBaseScopeProfiles();
    message.scope = (object.scope !== undefined && object.scope !== null)
      ? InstrumentationScope.fromPartial(object.scope)
      : undefined;
    message.profiles = object.profiles?.map((e) => Profile.fromPartial(e)) || [];
    message.schemaUrl = object.schemaUrl ?? "";
    return message;
  },
};

function createBaseProfile(): Profile {
  return {
    sampleType: undefined,
    samples: [],
    timeUnixNano: "0",
    durationNano: "0",
    periodType: undefined,
    period: "0",
    profileId: new Uint8Array(0),
    droppedAttributesCount: 0,
    originalPayloadFormat: "",
    originalPayload: new Uint8Array(0),
    attributeIndices: [],
  };
}

export const Profile: MessageFns<Profile> = {
  encode(message: Profile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sampleType !== undefined) {
      ValueType.encode(message.sampleType, writer.uint32(10).fork()).join();
    }
    for (const v of message.samples) {
      Sample.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.timeUnixNano !== "0") {
      writer.uint32(25).fixed64(message.timeUnixNano);
    }
    if (message.durationNano !== "0") {
      writer.uint32(32).uint64(message.durationNano);
    }
    if (message.periodType !== undefined) {
      ValueType.encode(message.periodType, writer.uint32(42).fork()).join();
    }
    if (message.period !== "0") {
      writer.uint32(48).int64(message.period);
    }
    if (message.profileId.length !== 0) {
      writer.uint32(58).bytes(message.profileId);
    }
    if (message.droppedAttributesCount !== 0) {
      writer.uint32(64).uint32(message.droppedAttributesCount);
    }
    if (message.originalPayloadFormat !== "") {
      writer.uint32(74).string(message.originalPayloadFormat);
    }
    if (message.originalPayload.length !== 0) {
      writer.uint32(82).bytes(message.originalPayload);
    }
    writer.uint32(90).fork();
    for (const v of message.attributeIndices) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Profile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProfile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sampleType = ValueType.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.samples.push(Sample.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.timeUnixNano = reader.fixed64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.durationNano = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.periodType = ValueType.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.period = reader.int64().toString();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.profileId = reader.bytes();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.droppedAttributesCount = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.originalPayloadFormat = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.originalPayload = reader.bytes();
          continue;
        }
        case 11: {
          if (tag === 88) {
            message.attributeIndices.push(reader.int32());

            continue;
          }

          if (tag === 90) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.attributeIndices.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Profile {
    return {
      sampleType: isSet(object.sampleType)
        ? ValueType.fromJSON(object.sampleType)
        : isSet(object.sample_type)
        ? ValueType.fromJSON(object.sample_type)
        : undefined,
      samples: globalThis.Array.isArray(object?.samples) ? object.samples.map((e: any) => Sample.fromJSON(e)) : [],
      timeUnixNano: isSet(object.timeUnixNano)
        ? globalThis.String(object.timeUnixNano)
        : isSet(object.time_unix_nano)
        ? globalThis.String(object.time_unix_nano)
        : "0",
      durationNano: isSet(object.durationNano)
        ? globalThis.String(object.durationNano)
        : isSet(object.duration_nano)
        ? globalThis.String(object.duration_nano)
        : "0",
      periodType: isSet(object.periodType)
        ? ValueType.fromJSON(object.periodType)
        : isSet(object.period_type)
        ? ValueType.fromJSON(object.period_type)
        : undefined,
      period: isSet(object.period) ? globalThis.String(object.period) : "0",
      profileId: isSet(object.profileId)
        ? bytesFromBase64(object.profileId)
        : isSet(object.profile_id)
        ? bytesFromBase64(object.profile_id)
        : new Uint8Array(0),
      droppedAttributesCount: isSet(object.droppedAttributesCount)
        ? globalThis.Number(object.droppedAttributesCount)
        : isSet(object.dropped_attributes_count)
        ? globalThis.Number(object.dropped_attributes_count)
        : 0,
      originalPayloadFormat: isSet(object.originalPayloadFormat)
        ? globalThis.String(object.originalPayloadFormat)
        : isSet(object.original_payload_format)
        ? globalThis.String(object.original_payload_format)
        : "",
      originalPayload: isSet(object.originalPayload)
        ? bytesFromBase64(object.originalPayload)
        : isSet(object.original_payload)
        ? bytesFromBase64(object.original_payload)
        : new Uint8Array(0),
      attributeIndices: globalThis.Array.isArray(object?.attributeIndices)
        ? object.attributeIndices.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.attribute_indices)
        ? object.attribute_indices.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: Profile): unknown {
    const obj: any = {};
    if (message.sampleType !== undefined) {
      obj.sampleType = ValueType.toJSON(message.sampleType);
    }
    if (message.samples?.length) {
      obj.samples = message.samples.map((e) => Sample.toJSON(e));
    }
    if (message.timeUnixNano !== "0") {
      obj.timeUnixNano = message.timeUnixNano;
    }
    if (message.durationNano !== "0") {
      obj.durationNano = message.durationNano;
    }
    if (message.periodType !== undefined) {
      obj.periodType = ValueType.toJSON(message.periodType);
    }
    if (message.period !== "0") {
      obj.period = message.period;
    }
    if (message.profileId.length !== 0) {
      obj.profileId = base64FromBytes(message.profileId);
    }
    if (message.droppedAttributesCount !== 0) {
      obj.droppedAttributesCount = Math.round(message.droppedAttributesCount);
    }
    if (message.originalPayloadFormat !== "") {
      obj.originalPayloadFormat = message.originalPayloadFormat;
    }
    if (message.originalPayload.length !== 0) {
      obj.originalPayload = base64FromBytes(message.originalPayload);
    }
    if (message.attributeIndices?.length) {
      obj.attributeIndices = message.attributeIndices.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Profile>, I>>(base?: I): Profile {
    return Profile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Profile>, I>>(object: I): Profile {
    const message = createBaseProfile();
    message.sampleType = (object.sampleType !== undefined && object.sampleType !== null)
      ? ValueType.fromPartial(object.sampleType)
      : undefined;
    message.samples = object.samples?.map((e) => Sample.fromPartial(e)) || [];
    message.timeUnixNano = object.timeUnixNano ?? "0";
    message.durationNano = object.durationNano ?? "0";
    message.periodType = (object.periodType !== undefined && object.periodType !== null)
      ? ValueType.fromPartial(object.periodType)
      : undefined;
    message.period = object.period ?? "0";
    message.profileId = object.profileId ?? new Uint8Array(0);
    message.droppedAttributesCount = object.droppedAttributesCount ?? 0;
    message.originalPayloadFormat = object.originalPayloadFormat ?? "";
    message.originalPayload = object.originalPayload ?? new Uint8Array(0);
    message.attributeIndices = object.attributeIndices?.map((e) => e) || [];
    return message;
  },
};

function createBaseLink(): Link {
  return { traceId: new Uint8Array(0), spanId: new Uint8Array(0) };
}

export const Link: MessageFns<Link> = {
  encode(message: Link, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.traceId.length !== 0) {
      writer.uint32(10).bytes(message.traceId);
    }
    if (message.spanId.length !== 0) {
      writer.uint32(18).bytes(message.spanId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Link {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLink();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.traceId = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.spanId = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Link {
    return {
      traceId: isSet(object.traceId)
        ? bytesFromBase64(object.traceId)
        : isSet(object.trace_id)
        ? bytesFromBase64(object.trace_id)
        : new Uint8Array(0),
      spanId: isSet(object.spanId)
        ? bytesFromBase64(object.spanId)
        : isSet(object.span_id)
        ? bytesFromBase64(object.span_id)
        : new Uint8Array(0),
    };
  },

  toJSON(message: Link): unknown {
    const obj: any = {};
    if (message.traceId.length !== 0) {
      obj.traceId = base64FromBytes(message.traceId);
    }
    if (message.spanId.length !== 0) {
      obj.spanId = base64FromBytes(message.spanId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Link>, I>>(base?: I): Link {
    return Link.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Link>, I>>(object: I): Link {
    const message = createBaseLink();
    message.traceId = object.traceId ?? new Uint8Array(0);
    message.spanId = object.spanId ?? new Uint8Array(0);
    return message;
  },
};

function createBaseValueType(): ValueType {
  return { typeStrindex: 0, unitStrindex: 0 };
}

export const ValueType: MessageFns<ValueType> = {
  encode(message: ValueType, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.typeStrindex !== 0) {
      writer.uint32(8).int32(message.typeStrindex);
    }
    if (message.unitStrindex !== 0) {
      writer.uint32(16).int32(message.unitStrindex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValueType {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValueType();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.typeStrindex = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.unitStrindex = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValueType {
    return {
      typeStrindex: isSet(object.typeStrindex)
        ? globalThis.Number(object.typeStrindex)
        : isSet(object.type_strindex)
        ? globalThis.Number(object.type_strindex)
        : 0,
      unitStrindex: isSet(object.unitStrindex)
        ? globalThis.Number(object.unitStrindex)
        : isSet(object.unit_strindex)
        ? globalThis.Number(object.unit_strindex)
        : 0,
    };
  },

  toJSON(message: ValueType): unknown {
    const obj: any = {};
    if (message.typeStrindex !== 0) {
      obj.typeStrindex = Math.round(message.typeStrindex);
    }
    if (message.unitStrindex !== 0) {
      obj.unitStrindex = Math.round(message.unitStrindex);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValueType>, I>>(base?: I): ValueType {
    return ValueType.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValueType>, I>>(object: I): ValueType {
    const message = createBaseValueType();
    message.typeStrindex = object.typeStrindex ?? 0;
    message.unitStrindex = object.unitStrindex ?? 0;
    return message;
  },
};

function createBaseSample(): Sample {
  return { stackIndex: 0, values: [], attributeIndices: [], linkIndex: 0, timestampsUnixNano: [] };
}

export const Sample: MessageFns<Sample> = {
  encode(message: Sample, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stackIndex !== 0) {
      writer.uint32(8).int32(message.stackIndex);
    }
    writer.uint32(18).fork();
    for (const v of message.values) {
      writer.int64(v);
    }
    writer.join();
    writer.uint32(26).fork();
    for (const v of message.attributeIndices) {
      writer.int32(v);
    }
    writer.join();
    if (message.linkIndex !== 0) {
      writer.uint32(32).int32(message.linkIndex);
    }
    writer.uint32(42).fork();
    for (const v of message.timestampsUnixNano) {
      writer.fixed64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Sample {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSample();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.stackIndex = reader.int32();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.values.push(reader.int64().toString());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.values.push(reader.int64().toString());
            }

            continue;
          }

          break;
        }
        case 3: {
          if (tag === 24) {
            message.attributeIndices.push(reader.int32());

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.attributeIndices.push(reader.int32());
            }

            continue;
          }

          break;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.linkIndex = reader.int32();
          continue;
        }
        case 5: {
          if (tag === 41) {
            message.timestampsUnixNano.push(reader.fixed64().toString());

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.timestampsUnixNano.push(reader.fixed64().toString());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Sample {
    return {
      stackIndex: isSet(object.stackIndex)
        ? globalThis.Number(object.stackIndex)
        : isSet(object.stack_index)
        ? globalThis.Number(object.stack_index)
        : 0,
      values: globalThis.Array.isArray(object?.values) ? object.values.map((e: any) => globalThis.String(e)) : [],
      attributeIndices: globalThis.Array.isArray(object?.attributeIndices)
        ? object.attributeIndices.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.attribute_indices)
        ? object.attribute_indices.map((e: any) => globalThis.Number(e))
        : [],
      linkIndex: isSet(object.linkIndex)
        ? globalThis.Number(object.linkIndex)
        : isSet(object.link_index)
        ? globalThis.Number(object.link_index)
        : 0,
      timestampsUnixNano: globalThis.Array.isArray(object?.timestampsUnixNano)
        ? object.timestampsUnixNano.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.timestamps_unix_nano)
        ? object.timestamps_unix_nano.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: Sample): unknown {
    const obj: any = {};
    if (message.stackIndex !== 0) {
      obj.stackIndex = Math.round(message.stackIndex);
    }
    if (message.values?.length) {
      obj.values = message.values;
    }
    if (message.attributeIndices?.length) {
      obj.attributeIndices = message.attributeIndices.map((e) => Math.round(e));
    }
    if (message.linkIndex !== 0) {
      obj.linkIndex = Math.round(message.linkIndex);
    }
    if (message.timestampsUnixNano?.length) {
      obj.timestampsUnixNano = message.timestampsUnixNano;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Sample>, I>>(base?: I): Sample {
    return Sample.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Sample>, I>>(object: I): Sample {
    const message = createBaseSample();
    message.stackIndex = object.stackIndex ?? 0;
    message.values = object.values?.map((e) => e) || [];
    message.attributeIndices = object.attributeIndices?.map((e) => e) || [];
    message.linkIndex = object.linkIndex ?? 0;
    message.timestampsUnixNano = object.timestampsUnixNano?.map((e) => e) || [];
    return message;
  },
};

function createBaseMapping(): Mapping {
  return { memoryStart: "0", memoryLimit: "0", fileOffset: "0", filenameStrindex: 0, attributeIndices: [] };
}

export const Mapping: MessageFns<Mapping> = {
  encode(message: Mapping, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.memoryStart !== "0") {
      writer.uint32(8).uint64(message.memoryStart);
    }
    if (message.memoryLimit !== "0") {
      writer.uint32(16).uint64(message.memoryLimit);
    }
    if (message.fileOffset !== "0") {
      writer.uint32(24).uint64(message.fileOffset);
    }
    if (message.filenameStrindex !== 0) {
      writer.uint32(32).int32(message.filenameStrindex);
    }
    writer.uint32(42).fork();
    for (const v of message.attributeIndices) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Mapping {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMapping();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.memoryStart = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.memoryLimit = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.fileOffset = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.filenameStrindex = reader.int32();
          continue;
        }
        case 5: {
          if (tag === 40) {
            message.attributeIndices.push(reader.int32());

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.attributeIndices.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Mapping {
    return {
      memoryStart: isSet(object.memoryStart)
        ? globalThis.String(object.memoryStart)
        : isSet(object.memory_start)
        ? globalThis.String(object.memory_start)
        : "0",
      memoryLimit: isSet(object.memoryLimit)
        ? globalThis.String(object.memoryLimit)
        : isSet(object.memory_limit)
        ? globalThis.String(object.memory_limit)
        : "0",
      fileOffset: isSet(object.fileOffset)
        ? globalThis.String(object.fileOffset)
        : isSet(object.file_offset)
        ? globalThis.String(object.file_offset)
        : "0",
      filenameStrindex: isSet(object.filenameStrindex)
        ? globalThis.Number(object.filenameStrindex)
        : isSet(object.filename_strindex)
        ? globalThis.Number(object.filename_strindex)
        : 0,
      attributeIndices: globalThis.Array.isArray(object?.attributeIndices)
        ? object.attributeIndices.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.attribute_indices)
        ? object.attribute_indices.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: Mapping): unknown {
    const obj: any = {};
    if (message.memoryStart !== "0") {
      obj.memoryStart = message.memoryStart;
    }
    if (message.memoryLimit !== "0") {
      obj.memoryLimit = message.memoryLimit;
    }
    if (message.fileOffset !== "0") {
      obj.fileOffset = message.fileOffset;
    }
    if (message.filenameStrindex !== 0) {
      obj.filenameStrindex = Math.round(message.filenameStrindex);
    }
    if (message.attributeIndices?.length) {
      obj.attributeIndices = message.attributeIndices.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Mapping>, I>>(base?: I): Mapping {
    return Mapping.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Mapping>, I>>(object: I): Mapping {
    const message = createBaseMapping();
    message.memoryStart = object.memoryStart ?? "0";
    message.memoryLimit = object.memoryLimit ?? "0";
    message.fileOffset = object.fileOffset ?? "0";
    message.filenameStrindex = object.filenameStrindex ?? 0;
    message.attributeIndices = object.attributeIndices?.map((e) => e) || [];
    return message;
  },
};

function createBaseStack(): Stack {
  return { locationIndices: [] };
}

export const Stack: MessageFns<Stack> = {
  encode(message: Stack, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.locationIndices) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Stack {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStack();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.locationIndices.push(reader.int32());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.locationIndices.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Stack {
    return {
      locationIndices: globalThis.Array.isArray(object?.locationIndices)
        ? object.locationIndices.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.location_indices)
        ? object.location_indices.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: Stack): unknown {
    const obj: any = {};
    if (message.locationIndices?.length) {
      obj.locationIndices = message.locationIndices.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Stack>, I>>(base?: I): Stack {
    return Stack.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Stack>, I>>(object: I): Stack {
    const message = createBaseStack();
    message.locationIndices = object.locationIndices?.map((e) => e) || [];
    return message;
  },
};

function createBaseLocation(): Location {
  return { mappingIndex: 0, address: "0", lines: [], attributeIndices: [] };
}

export const Location: MessageFns<Location> = {
  encode(message: Location, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mappingIndex !== 0) {
      writer.uint32(8).int32(message.mappingIndex);
    }
    if (message.address !== "0") {
      writer.uint32(16).uint64(message.address);
    }
    for (const v of message.lines) {
      Line.encode(v!, writer.uint32(26).fork()).join();
    }
    writer.uint32(34).fork();
    for (const v of message.attributeIndices) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Location {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLocation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.mappingIndex = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.address = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.lines.push(Line.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag === 32) {
            message.attributeIndices.push(reader.int32());

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.attributeIndices.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Location {
    return {
      mappingIndex: isSet(object.mappingIndex)
        ? globalThis.Number(object.mappingIndex)
        : isSet(object.mapping_index)
        ? globalThis.Number(object.mapping_index)
        : 0,
      address: isSet(object.address) ? globalThis.String(object.address) : "0",
      lines: globalThis.Array.isArray(object?.lines) ? object.lines.map((e: any) => Line.fromJSON(e)) : [],
      attributeIndices: globalThis.Array.isArray(object?.attributeIndices)
        ? object.attributeIndices.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.attribute_indices)
        ? object.attribute_indices.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: Location): unknown {
    const obj: any = {};
    if (message.mappingIndex !== 0) {
      obj.mappingIndex = Math.round(message.mappingIndex);
    }
    if (message.address !== "0") {
      obj.address = message.address;
    }
    if (message.lines?.length) {
      obj.lines = message.lines.map((e) => Line.toJSON(e));
    }
    if (message.attributeIndices?.length) {
      obj.attributeIndices = message.attributeIndices.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Location>, I>>(base?: I): Location {
    return Location.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Location>, I>>(object: I): Location {
    const message = createBaseLocation();
    message.mappingIndex = object.mappingIndex ?? 0;
    message.address = object.address ?? "0";
    message.lines = object.lines?.map((e) => Line.fromPartial(e)) || [];
    message.attributeIndices = object.attributeIndices?.map((e) => e) || [];
    return message;
  },
};

function createBaseLine(): Line {
  return { functionIndex: 0, line: "0", column: "0" };
}

export const Line: MessageFns<Line> = {
  encode(message: Line, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.functionIndex !== 0) {
      writer.uint32(8).int32(message.functionIndex);
    }
    if (message.line !== "0") {
      writer.uint32(16).int64(message.line);
    }
    if (message.column !== "0") {
      writer.uint32(24).int64(message.column);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Line {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLine();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.functionIndex = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.line = reader.int64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.column = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Line {
    return {
      functionIndex: isSet(object.functionIndex)
        ? globalThis.Number(object.functionIndex)
        : isSet(object.function_index)
        ? globalThis.Number(object.function_index)
        : 0,
      line: isSet(object.line) ? globalThis.String(object.line) : "0",
      column: isSet(object.column) ? globalThis.String(object.column) : "0",
    };
  },

  toJSON(message: Line): unknown {
    const obj: any = {};
    if (message.functionIndex !== 0) {
      obj.functionIndex = Math.round(message.functionIndex);
    }
    if (message.line !== "0") {
      obj.line = message.line;
    }
    if (message.column !== "0") {
      obj.column = message.column;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Line>, I>>(base?: I): Line {
    return Line.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Line>, I>>(object: I): Line {
    const message = createBaseLine();
    message.functionIndex = object.functionIndex ?? 0;
    message.line = object.line ?? "0";
    message.column = object.column ?? "0";
    return message;
  },
};

function createBaseFunctionMessage(): FunctionMessage {
  return { nameStrindex: 0, systemNameStrindex: 0, filenameStrindex: 0, startLine: "0" };
}

export const FunctionMessage: MessageFns<FunctionMessage> = {
  encode(message: FunctionMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nameStrindex !== 0) {
      writer.uint32(8).int32(message.nameStrindex);
    }
    if (message.systemNameStrindex !== 0) {
      writer.uint32(16).int32(message.systemNameStrindex);
    }
    if (message.filenameStrindex !== 0) {
      writer.uint32(24).int32(message.filenameStrindex);
    }
    if (message.startLine !== "0") {
      writer.uint32(32).int64(message.startLine);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FunctionMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFunctionMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.nameStrindex = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.systemNameStrindex = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.filenameStrindex = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.startLine = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FunctionMessage {
    return {
      nameStrindex: isSet(object.nameStrindex)
        ? globalThis.Number(object.nameStrindex)
        : isSet(object.name_strindex)
        ? globalThis.Number(object.name_strindex)
        : 0,
      systemNameStrindex: isSet(object.systemNameStrindex)
        ? globalThis.Number(object.systemNameStrindex)
        : isSet(object.system_name_strindex)
        ? globalThis.Number(object.system_name_strindex)
        : 0,
      filenameStrindex: isSet(object.filenameStrindex)
        ? globalThis.Number(object.filenameStrindex)
        : isSet(object.filename_strindex)
        ? globalThis.Number(object.filename_strindex)
        : 0,
      startLine: isSet(object.startLine)
        ? globalThis.String(object.startLine)
        : isSet(object.start_line)
        ? globalThis.String(object.start_line)
        : "0",
    };
  },

  toJSON(message: FunctionMessage): unknown {
    const obj: any = {};
    if (message.nameStrindex !== 0) {
      obj.nameStrindex = Math.round(message.nameStrindex);
    }
    if (message.systemNameStrindex !== 0) {
      obj.systemNameStrindex = Math.round(message.systemNameStrindex);
    }
    if (message.filenameStrindex !== 0) {
      obj.filenameStrindex = Math.round(message.filenameStrindex);
    }
    if (message.startLine !== "0") {
      obj.startLine = message.startLine;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FunctionMessage>, I>>(base?: I): FunctionMessage {
    return FunctionMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FunctionMessage>, I>>(object: I): FunctionMessage {
    const message = createBaseFunctionMessage();
    message.nameStrindex = object.nameStrindex ?? 0;
    message.systemNameStrindex = object.systemNameStrindex ?? 0;
    message.filenameStrindex = object.filenameStrindex ?? 0;
    message.startLine = object.startLine ?? "0";
    return message;
  },
};

function createBaseKeyValueAndUnit(): KeyValueAndUnit {
  return { keyStrindex: 0, value: undefined, unitStrindex: 0 };
}

export const KeyValueAndUnit: MessageFns<KeyValueAndUnit> = {
  encode(message: KeyValueAndUnit, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.keyStrindex !== 0) {
      writer.uint32(8).int32(message.keyStrindex);
    }
    if (message.value !== undefined) {
      AnyValue.encode(message.value, writer.uint32(18).fork()).join();
    }
    if (message.unitStrindex !== 0) {
      writer.uint32(24).int32(message.unitStrindex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): KeyValueAndUnit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeyValueAndUnit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.keyStrindex = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = AnyValue.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.unitStrindex = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): KeyValueAndUnit {
    return {
      keyStrindex: isSet(object.keyStrindex)
        ? globalThis.Number(object.keyStrindex)
        : isSet(object.key_strindex)
        ? globalThis.Number(object.key_strindex)
        : 0,
      value: isSet(object.value) ? AnyValue.fromJSON(object.value) : undefined,
      unitStrindex: isSet(object.unitStrindex)
        ? globalThis.Number(object.unitStrindex)
        : isSet(object.unit_strindex)
        ? globalThis.Number(object.unit_strindex)
        : 0,
    };
  },

  toJSON(message: KeyValueAndUnit): unknown {
    const obj: any = {};
    if (message.keyStrindex !== 0) {
      obj.keyStrindex = Math.round(message.keyStrindex);
    }
    if (message.value !== undefined) {
      obj.value = AnyValue.toJSON(message.value);
    }
    if (message.unitStrindex !== 0) {
      obj.unitStrindex = Math.round(message.unitStrindex);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KeyValueAndUnit>, I>>(base?: I): KeyValueAndUnit {
    return KeyValueAndUnit.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KeyValueAndUnit>, I>>(object: I): KeyValueAndUnit {
    const message = createBaseKeyValueAndUnit();
    message.keyStrindex = object.keyStrindex ?? 0;
    message.value = (object.value !== undefined && object.value !== null)
      ? AnyValue.fromPartial(object.value)
      : undefined;
    message.unitStrindex = object.unitStrindex ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
