package audit

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// uninstrumentedReport mirrors the $otel-audit output for a service with no
// OpenTelemetry at all (the checkout demo before $otel-instrument).
const uninstrumentedReport = `# Observability Report: checkout

**Language:** Python (>=3.11) | **Framework:** FastAPI | **Date:** 2026-08-26

## Current Instrumentation

### Spans

No spans detected.

### Metrics

No metrics detected.

### Logs

No OTel log instrumentation detected.

## RED Signals

| Signal | Status | Detail |
|--------|--------|--------|
| Rate | missing | No request-count source. |
| Errors | missing | No span status codes. |
| Duration | missing | No histogram. |

## Gaps
- fastapi has no instrumentation package.
- httpx has no instrumentation package.
- stdlib logging has no instrumentation package.
- No OTel SDK bootstrap.
- No OTEL_EXPORTER_OTLP_ENDPOINT configured.
- No service.name resource attribute.

## Anti-Patterns
- OTEL_SERVICE_NAME set with no SDK to read it.
- No record_exception in error handling.

## Recommendation
- Run $otel-instrument to add auto-instrumentation.

---
*Generated by obstudio v0.6.0 otel-audit on 2026-08-26 20:33 UTC*
`

// instrumentedReport mirrors the same service after $otel-instrument, including
// an Anti-Patterns section that opens with "None detected." and then adds
// context bullets — those must not be counted as live findings.
const instrumentedReport = `# Observability Report: checkout

**Language:** Python (>=3.11) | **Framework:** FastAPI (ASGI, served by uvicorn) | **Date:** 2026-08-26

## Current Instrumentation

### Spans

| Name | Source | Type |
|------|--------|------|
| GET /health | opentelemetry-instrumentation-fastapi | auto |
| GET /cart | opentelemetry-instrumentation-fastapi | auto |
| POST /checkout | opentelemetry-instrumentation-fastapi | auto |
| POST /payment | opentelemetry-instrumentation-fastapi | auto |

### Metrics

| Name | Source | Type |
|------|--------|------|
| http.server.duration | opentelemetry-instrumentation-asgi | auto |
| http.server.active_requests | opentelemetry-instrumentation-asgi | auto |

### Logs

| Integration | Source | Detail |
|-------------|--------|--------|
| trace-context injection | otel_setup.py | Adds trace_id/span_id to log records |

## RED Signals

| Signal | Status | Detail |
|--------|--------|--------|
| Rate | covered | http.server.duration histogram count. |
| Errors | covered | 5xx sets span status ERROR. |
| Duration | covered | Histogram percentiles per route. |

## Gaps
- No OTLP log pipeline.
- httpx still has no instrumentation package.
- No business-outcome spans beyond HTTP status.

## Anti-Patterns
- None detected.
- Previously flagged and now resolved: OTEL_SERVICE_NAME with no SDK.
- Providers are constructed once at startup.
- No hardcoded endpoints.

## Recommendation
- Instrumentation is complete for RED.
- Consider adding an OTLP log pipeline.

---
*Generated by obstudio v0.6.0 otel-audit on 2026-08-26 20:52 UTC*
`

func TestParseUninstrumentedReport(t *testing.T) {
	got := Parse(uninstrumentedReport)

	if got.ServiceName != "checkout" {
		t.Errorf("ServiceName = %q, want %q", got.ServiceName, "checkout")
	}
	if got.Language != "Python (>=3.11)" {
		t.Errorf("Language = %q", got.Language)
	}
	if got.Rate != REDMissing || got.Errors != REDMissing || got.Duration != REDMissing {
		t.Errorf("RED = %s/%s/%s, want all missing", got.Rate, got.Errors, got.Duration)
	}
	if got.HasSpans || got.HasMetrics || got.HasLogs {
		t.Errorf("signals = spans:%v metrics:%v logs:%v, want all false", got.HasSpans, got.HasMetrics, got.HasLogs)
	}
	if got.GapCount != 6 {
		t.Errorf("GapCount = %d, want 6", got.GapCount)
	}
	if got.AntiPatternCount != 2 {
		t.Errorf("AntiPatternCount = %d, want 2", got.AntiPatternCount)
	}

	// Coverage 0; quality = anti-patterns max(0, 15-10)=5, gaps max(0, 15-18)=0.
	if got.Score != 5 {
		t.Errorf("Score = %d, want 5", got.Score)
	}
}

func TestParseInstrumentedReport(t *testing.T) {
	got := Parse(instrumentedReport)

	if got.Rate != REDCovered || got.Errors != REDCovered || got.Duration != REDCovered {
		t.Errorf("RED = %s/%s/%s, want all covered", got.Rate, got.Errors, got.Duration)
	}
	if !got.HasSpans || !got.HasMetrics || !got.HasLogs {
		t.Errorf("signals = spans:%v metrics:%v logs:%v, want all true", got.HasSpans, got.HasMetrics, got.HasLogs)
	}
	if got.GapCount != 3 {
		t.Errorf("GapCount = %d, want 3", got.GapCount)
	}
	if got.RecommendationCount != 2 {
		t.Errorf("RecommendationCount = %d, want 2", got.RecommendationCount)
	}
	if len(got.Gaps) != 3 || got.Gaps[0] != "No OTLP log pipeline." {
		t.Errorf("Gaps = %q, want the three gap sentences", got.Gaps)
	}
	if len(got.Recommendations) != 2 || got.Recommendations[0] != "Instrumentation is complete for RED." {
		t.Errorf("Recommendations = %q", got.Recommendations)
	}
	// "None detected." suppresses the section, so no bullet text leaks through.
	if len(got.AntiPatterns) != 0 {
		t.Errorf("AntiPatterns = %q, want none", got.AntiPatterns)
	}

	// Coverage 45+10+10+5=70; quality = 15 (no anti-patterns) + max(0,15-9)=6.
	if got.Score != 91 {
		t.Errorf("Score = %d, want 91", got.Score)
	}
	if got.Breakdown.Coverage != 70 {
		t.Errorf("Coverage = %v, want 70", got.Breakdown.Coverage)
	}
	if got.Breakdown.Quality != 21 {
		t.Errorf("Quality = %v, want 21", got.Breakdown.Quality)
	}
}

// A chatty Anti-Patterns section that says "None detected" and then adds
// explanatory bullets must score as zero anti-patterns, not four.
func TestNoneDetectedBeatsSurroundingBullets(t *testing.T) {
	got := Parse(instrumentedReport)

	if got.AntiPatternCount != 0 {
		t.Errorf("AntiPatternCount = %d, want 0 despite context bullets", got.AntiPatternCount)
	}
}

func TestPartialSignalsScoreHalf(t *testing.T) {
	report := strings.Replace(instrumentedReport, "| Rate | covered |", "| Rate | partial |", 1)
	got := Parse(report)

	if got.Rate != REDPartial {
		t.Fatalf("Rate = %s, want partial", got.Rate)
	}
	// 91 - 7.5 = 83.5, rounds to 84.
	if got.Score != 84 {
		t.Errorf("Score = %d, want 84", got.Score)
	}
}

func TestScoreIsBounded(t *testing.T) {
	manyGaps := strings.Replace(uninstrumentedReport, "## Gaps\n", "## Gaps\n"+strings.Repeat("- another gap\n", 50), 1)
	got := Parse(manyGaps)

	if got.Score < 0 || got.Score > 100 {
		t.Errorf("Score = %d, want within [0,100]", got.Score)
	}
}

func TestBuildMissingReport(t *testing.T) {
	r := NewResolver(Config{WorkspaceRoot: t.TempDir()})
	got := r.Build()

	if got.Available {
		t.Error("Available = true, want false for a missing report")
	}
	if !strings.Contains(got.Message, "$otel-audit") {
		t.Errorf("Message = %q, want it to name $otel-audit", got.Message)
	}
	// The absolute path must not leak through this CORS-open endpoint.
	if strings.Contains(got.Message, string(filepath.Separator)+"tmp") || filepath.IsAbs(got.Source) {
		t.Errorf("Message/Source leaked an absolute path: %q / %q", got.Message, got.Source)
	}
}

func TestBuildReadsReport(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, ".observe"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, ".observe", "otel.md"), []byte(instrumentedReport), 0o600); err != nil {
		t.Fatal(err)
	}

	got := NewResolver(Config{WorkspaceRoot: root}).Build()

	if !got.Available {
		t.Fatalf("Available = false, message = %q", got.Message)
	}
	if got.Score != 91 {
		t.Errorf("Score = %d, want 91", got.Score)
	}
	if got.Source != "otel.md" {
		t.Errorf("Source = %q, want basename only", got.Source)
	}
}

func TestBuildRejectsMalformedReport(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, ".observe"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, ".observe", "otel.md"), []byte("# Some other document\n\nNothing useful.\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	got := NewResolver(Config{WorkspaceRoot: root}).Build()

	if got.Available {
		t.Error("Available = true, want false for a non-audit document")
	}
}

func TestResolverRejectsPathTraversal(t *testing.T) {
	root := t.TempDir()
	r := NewResolver(Config{WorkspaceRoot: root, ReportPath: "../../etc/passwd"})

	want := filepath.Join(root, DefaultReportRelPath)
	if r.reportPath != want {
		t.Errorf("reportPath = %q, want fallback %q", r.reportPath, want)
	}
}

func TestResolverRejectsAbsolutePathOutsideWorkspace(t *testing.T) {
	root := t.TempDir()
	r := NewResolver(Config{WorkspaceRoot: root, ReportPath: filepath.Join(t.TempDir(), "elsewhere.md")})

	want := filepath.Join(root, DefaultReportRelPath)
	if r.reportPath != want {
		t.Errorf("reportPath = %q, want fallback %q", r.reportPath, want)
	}
}

func TestCollectBulletsStripsMarkdownAndJoinsWraps(t *testing.T) {
	report := `# Observability Report: svc

## RED Signals

| Signal | Status | Detail |
|--------|--------|--------|
| Rate | covered | ok |

## Gaps
- ` + "`httpx`" + ` has no **instrumentation** package.
  This wrapped onto a second line.
- A second gap.

## Recommendation
- Run ` + "`$otel-instrument`" + `.
`

	got := Parse(report)

	if len(got.Gaps) != 2 {
		t.Fatalf("Gaps = %q, want 2", got.Gaps)
	}
	want := "httpx has no instrumentation package. This wrapped onto a second line."
	if got.Gaps[0] != want {
		t.Errorf("Gaps[0] = %q, want %q", got.Gaps[0], want)
	}
	if got.Recommendations[0] != "Run $otel-instrument." {
		t.Errorf("Recommendations[0] = %q", got.Recommendations[0])
	}
}

// A nil slice would marshal to null and break clients that iterate the field.
func TestFindingSlicesMarshalAsArrays(t *testing.T) {
	got := Parse(instrumentedReport)

	raw, err := json.Marshal(got)
	if err != nil {
		t.Fatal(err)
	}
	body := string(raw)

	for _, field := range []string{`"gaps":null`, `"antiPatterns":null`, `"recommendations":null`} {
		if strings.Contains(body, field) {
			t.Errorf("JSON contains %s; want an empty array instead", field)
		}
	}
	if !strings.Contains(body, `"antiPatterns":[]`) {
		t.Errorf("antiPatterns should marshal as [], got: %s", body)
	}
}

func TestReadRawReturnsSource(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, ".observe"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, ".observe", "otel.md"), []byte(instrumentedReport), 0o600); err != nil {
		t.Fatal(err)
	}

	r := NewResolver(Config{WorkspaceRoot: root})
	raw, err := r.ReadRaw()
	if err != nil {
		t.Fatalf("ReadRaw: %v", err)
	}
	if string(raw) != instrumentedReport {
		t.Error("ReadRaw returned different content than the file holds")
	}
	if r.Source() != "otel.md" {
		t.Errorf("Source() = %q, want basename only", r.Source())
	}
}

func TestReadRawMissingReport(t *testing.T) {
	r := NewResolver(Config{WorkspaceRoot: t.TempDir()})

	_, err := r.ReadRaw()
	if !errors.Is(err, ErrNoReport) {
		t.Errorf("err = %v, want ErrNoReport", err)
	}
}

// ReadRaw must obey the same traversal guard as Build.
func TestReadRawHonorsPathGuard(t *testing.T) {
	root := t.TempDir()
	outside := filepath.Join(t.TempDir(), "secret.md")
	if err := os.WriteFile(outside, []byte("# secret\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	r := NewResolver(Config{WorkspaceRoot: root, ReportPath: outside})

	_, err := r.ReadRaw()
	if !errors.Is(err, ErrNoReport) {
		t.Errorf("err = %v, want ErrNoReport (path outside workspace must not be read)", err)
	}
}
