// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.19.1
// source: opentelemetry/proto/collector/trace/v1/trace_service.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ResourceSpans } from "../../../trace/v1/trace.js";
function createBaseExportTraceServiceRequest() {
    return { resourceSpans: [] };
}
export const ExportTraceServiceRequest = {
    encode(message, writer = new BinaryWriter()) {
        for (const v of message.resourceSpans) {
            ResourceSpans.encode(v, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseExportTraceServiceRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.resourceSpans.push(ResourceSpans.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            resourceSpans: globalThis.Array.isArray(object?.resourceSpans)
                ? object.resourceSpans.map((e) => ResourceSpans.fromJSON(e))
                : globalThis.Array.isArray(object?.resource_spans)
                    ? object.resource_spans.map((e) => ResourceSpans.fromJSON(e))
                    : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.resourceSpans?.length) {
            obj.resourceSpans = message.resourceSpans.map((e) => ResourceSpans.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return ExportTraceServiceRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseExportTraceServiceRequest();
        message.resourceSpans = object.resourceSpans?.map((e) => ResourceSpans.fromPartial(e)) || [];
        return message;
    },
};
function createBaseExportTraceServiceResponse() {
    return { partialSuccess: undefined };
}
export const ExportTraceServiceResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.partialSuccess !== undefined) {
            ExportTracePartialSuccess.encode(message.partialSuccess, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseExportTraceServiceResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.partialSuccess = ExportTracePartialSuccess.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            partialSuccess: isSet(object.partialSuccess)
                ? ExportTracePartialSuccess.fromJSON(object.partialSuccess)
                : isSet(object.partial_success)
                    ? ExportTracePartialSuccess.fromJSON(object.partial_success)
                    : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.partialSuccess !== undefined) {
            obj.partialSuccess = ExportTracePartialSuccess.toJSON(message.partialSuccess);
        }
        return obj;
    },
    create(base) {
        return ExportTraceServiceResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseExportTraceServiceResponse();
        message.partialSuccess = (object.partialSuccess !== undefined && object.partialSuccess !== null)
            ? ExportTracePartialSuccess.fromPartial(object.partialSuccess)
            : undefined;
        return message;
    },
};
function createBaseExportTracePartialSuccess() {
    return { rejectedSpans: "0", errorMessage: "" };
}
export const ExportTracePartialSuccess = {
    encode(message, writer = new BinaryWriter()) {
        if (message.rejectedSpans !== "0") {
            writer.uint32(8).int64(message.rejectedSpans);
        }
        if (message.errorMessage !== "") {
            writer.uint32(18).string(message.errorMessage);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseExportTracePartialSuccess();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.rejectedSpans = reader.int64().toString();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.errorMessage = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            rejectedSpans: isSet(object.rejectedSpans)
                ? globalThis.String(object.rejectedSpans)
                : isSet(object.rejected_spans)
                    ? globalThis.String(object.rejected_spans)
                    : "0",
            errorMessage: isSet(object.errorMessage)
                ? globalThis.String(object.errorMessage)
                : isSet(object.error_message)
                    ? globalThis.String(object.error_message)
                    : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.rejectedSpans !== "0") {
            obj.rejectedSpans = message.rejectedSpans;
        }
        if (message.errorMessage !== "") {
            obj.errorMessage = message.errorMessage;
        }
        return obj;
    },
    create(base) {
        return ExportTracePartialSuccess.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseExportTracePartialSuccess();
        message.rejectedSpans = object.rejectedSpans ?? "0";
        message.errorMessage = object.errorMessage ?? "";
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
