// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.19.1
// source: opentelemetry/proto/resource/v1/resource.proto

/* eslint-disable */
import type { EntityRef, KeyValue } from "../../common/v1/common";

/** Resource information. */
export interface Resource {
  /**
   * Set of attributes that describe the resource.
   * Attribute keys MUST be unique (it is not allowed to have more than one
   * attribute with the same key).
   * The behavior of software that receives duplicated keys can be unpredictable.
   */
  attributes: KeyValue[];
  /**
   * The number of dropped attributes. If the value is 0, then
   * no attributes were dropped.
   */
  droppedAttributesCount: number;
  /**
   * Set of entities that participate in this Resource.
   *
   * Note: keys in the references MUST exist in attributes of this message.
   *
   * Status: [Development]
   */
  entityRefs: EntityRef[];
}
