#!/usr/bin/env bun
// Generates src/web/embedded-assets.ts from dist/static/ build output.
// Run after building the React client and before `bun build --compile`.

import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const STATIC_DIR = join(ROOT, "dist/static");

const indexHtml = await Bun.file(join(STATIC_DIR, "index.html")).text();
const mainCss = await Bun.file(join(STATIC_DIR, "assets/main.css")).text();
const mainJs = await Bun.file(join(STATIC_DIR, "assets/main.js")).text();

// Source maps are optional — don't embed if missing (they're large and only for dev).

const out = `// Auto-generated by scripts/embed-static.ts — do not edit.
// Contains the built React client assets embedded as strings.

export const indexHtml = ${JSON.stringify(indexHtml)};
export const assets: Record<string, { content: string; mime: string }> = {
  "/assets/main.css": { content: ${JSON.stringify(mainCss)}, mime: "text/css" },
  "/assets/main.js": { content: ${JSON.stringify(mainJs)}, mime: "application/javascript" },
};
`;

const outPath = join(ROOT, "src/web/embedded-assets.ts");
await Bun.write(outPath, out);
console.log(`Wrote ${outPath} (${(out.length / 1024).toFixed(0)} KB)`);
